package main

import (
	"fmt"
	"sort"
	"strings"
)

// ── Shell completion ──────────────────────────────────────────────────────────
//
// `hashsmith completion bash|zsh|fish` writes a completion script to stdout.
//
// This matters more here than for most tools: the CLI has sixteen commands,
// forty-seven extractors, twenty-five crack flags and over a thousand accepted
// type names. Without completion the only way to find a type is to read
// `hashsmith types` and copy by hand, which is exactly the friction that sends
// someone back to a tool they already have in their muscle memory.
//
// The type and codec lists are generated from the live registries rather than
// hardcoded, so a format added tomorrow completes without anyone remembering
// to update this file.

// completionCommands lists every command a completion script should offer,
// paired with a one-line description for the shells that show them.
func completionCommands() [][2]string {
	cmds := [][2]string{
		{"encode", "Encode input with a codec"},
		{"decode", "Decode input with a codec"},
		{"hash", "Hash input with an algorithm"},
		{"crack", "Recover the plaintext behind a hash"},
		{"identify", "Report which hash types an input could be"},
		{"selftest", "Verify the built-in known-answer vectors"},
		{"types", "List every supported -t hash type"},
		{"encodings", "List every supported encode/decode type"},
		{"extractors", "List the integrated *2smith extractors"},
		{"rules", "Preview and validate a mangling-rule file"},
		{"benchmark", "Measure native throughput"},
		{"gpu", "Show GPU acceleration status"},
		{"sessions", "Manage saved resumable sessions"},
		{"wordlists", "Show and pin the default wordlist"},
		{"interactive", "Guided interactive mode"},
		{"completion", "Emit a shell completion script"},
		{"version", "Print the version"},
	}
	for _, e := range universalExtractorRegistry {
		cmds = append(cmds, [2]string{e.name, e.input + " -> " + e.formats})
	}
	return cmds
}

// completionHashTypes returns every canonical -t hash name, sorted.
func completionHashTypes() []string {
	out := append([]string(nil), universalHashRegistry.order...)
	sort.Strings(out)
	return out
}

// completionCodecTypes returns every encode/decode -t name, sorted.
func completionCodecTypes() []string {
	var out []string
	for _, group := range codecCatalogue {
		for _, item := range group.items {
			out = append(out, item[0])
		}
	}
	sort.Strings(out)
	return out
}

func runCompletion(args []string) error {
	if len(args) == 0 || wantsHelp(args) {
		fmt.Println("Usage: hashsmith completion <bash|zsh|fish>")
		fmt.Println()
		fmt.Println("Write a completion script to stdout. To install it:")
		fmt.Println("  bash   hashsmith completion bash > /etc/bash_completion.d/hashsmith")
		fmt.Println("  zsh    hashsmith completion zsh  > \"${fpath[1]}/_hashsmith\"")
		fmt.Println("  fish   hashsmith completion fish > ~/.config/fish/completions/hashsmith.fish")
		return nil
	}
	switch strings.ToLower(args[0]) {
	case "bash":
		fmt.Print(bashCompletion())
	case "zsh":
		fmt.Print(zshCompletion())
	case "fish":
		fmt.Print(fishCompletion())
	default:
		return fmt.Errorf("unsupported shell %q (want bash, zsh or fish)", args[0])
	}
	return nil
}

func completionCommandNames() []string {
	var out []string
	for _, c := range completionCommands() {
		out = append(out, c[0])
	}
	return out
}

func bashCompletion() string {
	var b strings.Builder
	fmt.Fprintf(&b, "# bash completion for hashsmith. Generated by `hashsmith completion bash`.\n")
	fmt.Fprintf(&b, "_hashsmith() {\n")
	fmt.Fprintf(&b, "  local cur prev cmd\n")
	fmt.Fprintf(&b, "  cur=\"${COMP_WORDS[COMP_CWORD]}\"\n")
	fmt.Fprintf(&b, "  prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n")
	fmt.Fprintf(&b, "  cmd=\"${COMP_WORDS[1]}\"\n")
	fmt.Fprintf(&b, "  local commands=%q\n", strings.Join(completionCommandNames(), " "))
	fmt.Fprintf(&b, "  local hashtypes=%q\n", strings.Join(completionHashTypes(), " "))
	fmt.Fprintf(&b, "  local codectypes=%q\n", strings.Join(completionCodecTypes(), " "))
	b.WriteString(`  if [[ $COMP_CWORD -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "$commands" -- "$cur") )
    return
  fi
  # -t takes a hash type for hash/crack/identify and a codec for encode/decode.
  if [[ "$prev" == "-t" || "$prev" == "--type" ]]; then
    case "$cmd" in
      encode|decode) COMPREPLY=( $(compgen -W "$codectypes" -- "$cur") ) ;;
      *)             COMPREPLY=( $(compgen -W "$hashtypes" -- "$cur") ) ;;
    esac
    return
  fi
  # Flags that take a path complete as files.
  case "$prev" in
    -w|--wordlist|--wordlist2|-r|--rules|-o|--outfile|-f) COMPREPLY=( $(compgen -f -- "$cur") ); return ;;
  esac
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-t -w -o -c -s -S -M -r --rules --mask --session --restore --show --left --username --gpu --stdout --no-pot --split --help --version" -- "$cur") )
    return
  fi
  COMPREPLY=( $(compgen -f -- "$cur") )
}
complete -F _hashsmith hashsmith
`)
	return b.String()
}

func zshCompletion() string {
	var b strings.Builder
	b.WriteString("#compdef hashsmith\n")
	b.WriteString("# zsh completion for hashsmith. Generated by `hashsmith completion zsh`.\n\n")
	b.WriteString("_hashsmith() {\n  local -a commands hashtypes codectypes\n")
	b.WriteString("  commands=(\n")
	for _, c := range completionCommands() {
		fmt.Fprintf(&b, "    %s\n", zshQuote(c[0]+":"+c[1]))
	}
	b.WriteString("  )\n")
	fmt.Fprintf(&b, "  hashtypes=(%s)\n", strings.Join(completionHashTypes(), " "))
	fmt.Fprintf(&b, "  codectypes=(%s)\n", strings.Join(completionCodecTypes(), " "))
	b.WriteString(`  if (( CURRENT == 2 )); then
    _describe -t commands 'hashsmith command' commands
    return
  fi
  case "${words[2]}" in
    encode|decode)
      _arguments '-t[codec type]:codec:(${codectypes})' '-o[output file]:file:_files' '*:input:_files'
      ;;
    hash|crack|identify)
      _arguments '-t[hash type]:type:(${hashtypes})' \
                 '-w[wordlist]:file:_files' '-r[rule file]:file:_files' \
                 '-o[output file]:file:_files' '*:target:_files'
      ;;
    *)
      _files
      ;;
  esac
}
_hashsmith "$@"
`)
	return b.String()
}

// zshQuote renders one 'name:description' pair safely for a zsh array literal.
func zshQuote(s string) string {
	return "'" + strings.ReplaceAll(strings.ReplaceAll(s, `'`, `'\''`), "\n", " ") + "'"
}

func fishCompletion() string {
	var b strings.Builder
	b.WriteString("# fish completion for hashsmith. Generated by `hashsmith completion fish`.\n")
	b.WriteString("complete -c hashsmith -f\n")
	for _, c := range completionCommands() {
		fmt.Fprintf(&b, "complete -c hashsmith -n __fish_use_subcommand -a %s -d %s\n",
			fishQuote(c[0]), fishQuote(c[1]))
	}
	types := strings.Join(completionHashTypes(), " ")
	codecs := strings.Join(completionCodecTypes(), " ")
	fmt.Fprintf(&b, "complete -c hashsmith -n '__fish_seen_subcommand_from encode decode' -s t -x -a %s\n", fishQuote(codecs))
	fmt.Fprintf(&b, "complete -c hashsmith -n '__fish_seen_subcommand_from hash crack identify' -s t -x -a %s\n", fishQuote(types))
	b.WriteString("complete -c hashsmith -s w -l wordlist -r -F -d 'Wordlist file'\n")
	b.WriteString("complete -c hashsmith -s r -l rules -r -F -d 'Mangling-rule file'\n")
	b.WriteString("complete -c hashsmith -s o -l outfile -r -F -d 'Output file'\n")
	b.WriteString("complete -c hashsmith -s V -l version -d 'Print the version'\n")
	return b.String()
}

// fishQuote single-quotes a value for a fish completion argument.
func fishQuote(s string) string {
	return "'" + strings.ReplaceAll(strings.ReplaceAll(s, `\`, `\\`), `'`, `\'`) + "'"
}
