//go:build amd64

package main

import "encoding/binary"

// md4g24AVX2 is the pipelined 3-chain (24-way) AVX2 MD4 core; the assembly
// lives in md4avx2_amd64.s (generated by md4avx2_gen.py). Each chain c
// hashes 8 lanes at once from a single [16][8] word-major, lane-minor
// message block. out0..out2 receive that chain's final [4][8]uint32 state
// (word w, lane l): word w of chain c's lane l digest is out_c[w][l].
//
// It is the x86-64 counterpart of md4g20NEON (md4neon_arm64.go) and
// computes bit-identical digests. MD4 also backs NTLM here — NTLM is MD4
// over UTF-16LE(pw), not a different digest function, so only the encoding
// mode differs and both route through this same core.
//
// Unlike md5g24AVX2 there is no allones argument: MD4 needs no vector NOT
// anywhere. Its round 1 is the same function as MD5's round 1 and is
// computed by the NOT-free bit-select identity d^(b&(c^d)); its rounds 2
// and 3 (majority, xor) contain no complement; and it has no round 4, which
// is the only place MD5 needed one. md4neon_arm64.go's core dropped the
// same constant for the same reason.
//
// msg0..msg2 are declared *uint32 rather than *[16][8]uint32: the assembly
// only ever does byte-offset loads from the pointer it is given, so the
// pointee type is immaterial to it, and this lets callers pass
// &transposedBatch.words[c*128] directly — that slice is already laid out
// as [chains][16][lanes]uint32, exactly what each msg pointer expects —
// with no marshalling and no unsafe. go vet's asmdecl check compares
// argument sizes and FP offsets, which are identical for any pointer
// regardless of its Go pointee type, so this typing is vet-clean.
//
//go:noescape
func md4g24AVX2(out0, out1, out2 *[4][8]uint32, msg0, msg1, msg2 *uint32, kvec *[3][8]uint32, ivvec *[4][8]uint32)

// md4AVX2IsAssembly reports, as a build-time constant, that this build
// linked the real AVX2 assembly core rather than md4avx2_generic.go's
// scalar fallback. md4avx2_test.go's coverage guard reads it so that CI's
// amd64 lane fails loudly if it ever stops exercising the assembly — see
// TestMD4AVX2CoreWasActuallyExercised.
const md4AVX2IsAssembly = true

// md4AVX2Kvec holds MD4's 3 per-pass round constants, each pre-broadcast
// into all 8 AVX2 lanes so the core can VPADDD a whole vector against it.
// Unlike MD5's 64-entry per-step table, MD4's constant changes only 3 times
// per call (once per 16-step pass).
//
// Entry 0 is zero and is never read by the assembly: adding it would be the
// identity, so md4avx2_gen.py omits the pass-1 K add entirely rather than
// putting 16 no-op adds on each chain's serial dependency chain. It is kept
// here anyway so this table is indexed by pass number exactly as
// md4neon_arm64.go's md4Kvec is, rather than silently renumbered.
var md4AVX2Kvec = [3][8]uint32{
	{0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
	{0x5A827999, 0x5A827999, 0x5A827999, 0x5A827999, 0x5A827999, 0x5A827999, 0x5A827999, 0x5A827999},
	{0x6ED9EBA1, 0x6ED9EBA1, 0x6ED9EBA1, 0x6ED9EBA1, 0x6ED9EBA1, 0x6ED9EBA1, 0x6ED9EBA1, 0x6ED9EBA1},
}

// md4AVX2IVvec holds MD4's initial state (A,B,C,D) — numerically identical
// to MD5's IV — each broadcast into all 8 lanes, so every chain starts from
// the same chaining value.
var md4AVX2IVvec = [4][8]uint32{
	{0x67452301, 0x67452301, 0x67452301, 0x67452301, 0x67452301, 0x67452301, 0x67452301, 0x67452301},
	{0xefcdab89, 0xefcdab89, 0xefcdab89, 0xefcdab89, 0xefcdab89, 0xefcdab89, 0xefcdab89, 0xefcdab89},
	{0x98badcfe, 0x98badcfe, 0x98badcfe, 0x98badcfe, 0x98badcfe, 0x98badcfe, 0x98badcfe, 0x98badcfe},
	{0x10325476, 0x10325476, 0x10325476, 0x10325476, 0x10325476, 0x10325476, 0x10325476, 0x10325476},
}

// md4GroupAVX2 hashes all avx2Shape.group() (24) lanes of tb through the
// AVX2 MD4 core in one call. tb.words is already [chains][16][lanes]uint32
// flattened (see transposed.go), so chain c's message block is
// &tb.words[c*16*8] — no marshalling. Mirrors md5GroupAVX2 exactly.
func md4GroupAVX2(tb *transposedBatch, out [][16]byte) {
	const chainStride = 16 * 8
	var outs [3][4][8]uint32
	md4g24AVX2(
		&outs[0], &outs[1], &outs[2],
		&tb.words[0*chainStride], &tb.words[1*chainStride], &tb.words[2*chainStride],
		&md4AVX2Kvec, &md4AVX2IVvec,
	)
	for c := 0; c < 3; c++ {
		for l := 0; l < 8; l++ {
			i := c*8 + l
			for w := 0; w < 4; w++ {
				binary.LittleEndian.PutUint32(out[i][w*4:w*4+4], outs[c][w][l])
			}
		}
	}
}
