//go:build arm64

package main

import "encoding/binary"

// md4g20NEON is the pipelined 5-chain (20-way) NEON MD4 core; the assembly
// lives in md4neon_arm64.s (generated by md4neon_gen.py, adapted from the
// MD5 core's md5neon_gen.py). Each chain c hashes 4 lanes at once from a
// single [16][4] word-major, lane-minor message block. out0..out4 receive
// that chain's final [4][4]uint32 state (word w, lane l): word w of chain
// c's lane l digest is out_c[w][l].
//
// msg0..msg4 are declared *uint32 rather than *[16][4]uint32, mirroring
// md5g20NEON: the assembly only ever does byte-offset loads from the
// pointer it is given, so the pointee type is immaterial to it, and this
// lets callers pass &transposedBatch.words[c*64] directly — that slice is
// already laid out as [chains][16][lanes]uint32, exactly what each msg
// pointer expects — with no marshalling and no unsafe. go vet's asmdecl
// check compares argument sizes and FP offsets, which are identical for
// any pointer regardless of its Go pointee type, so this typing is
// vet-clean.
//
//go:noescape
func md4g20NEON(out0, out1, out2, out3, out4 *[4][4]uint32, msg0, msg1, msg2, msg3, msg4 *uint32, kvec *[3][4]uint32, ivvec *[4][4]uint32)

// md4Kvec holds the 3 MD4 per-pass round constants (0, 0x5A827999,
// 0x6ED9EBA1), each pre-broadcast into all 4 NEON lanes so the core can
// VADD a whole vector against it per step. Unlike MD5's 64-entry table,
// MD4's constant only changes 3 times per call (once per 16-step pass),
// not once per step.
var md4Kvec = [3][4]uint32{
	{0x00000000, 0x00000000, 0x00000000, 0x00000000},
	{0x5A827999, 0x5A827999, 0x5A827999, 0x5A827999},
	{0x6ED9EBA1, 0x6ED9EBA1, 0x6ED9EBA1, 0x6ED9EBA1},
}

// md4IVvec holds MD4's initial state (A,B,C,D) — numerically identical to
// MD5's IV — each broadcast into all 4 lanes, so every chain starts from
// the same chaining value.
var md4IVvec = [4][4]uint32{
	{0x67452301, 0x67452301, 0x67452301, 0x67452301},
	{0xefcdab89, 0xefcdab89, 0xefcdab89, 0xefcdab89},
	{0x98badcfe, 0x98badcfe, 0x98badcfe, 0x98badcfe},
	{0x10325476, 0x10325476, 0x10325476, 0x10325476},
}

// md4Group hashes all neonGroup lanes of tb through the NEON core in one
// call. tb.words is already [neonChains][16][neonLanes]uint32 flattened
// (see transposed.go), so chain c's message block is simply
// &tb.words[c*64] — no marshalling.
func md4Group(tb *transposedBatch, out *[neonGroup][16]byte) {
	var outs [neonChains][4][4]uint32
	md4g20NEON(
		&outs[0], &outs[1], &outs[2], &outs[3], &outs[4],
		&tb.words[0*64], &tb.words[1*64], &tb.words[2*64], &tb.words[3*64], &tb.words[4*64],
		&md4Kvec, &md4IVvec,
	)
	for c := 0; c < neonChains; c++ {
		for l := 0; l < neonLanes; l++ {
			i := c*neonLanes + l
			for w := 0; w < 4; w++ {
				binary.LittleEndian.PutUint32(out[i][w*4:w*4+4], outs[c][w][l])
			}
		}
	}
}

// md4GroupAccelerated reports whether this build has the vector core, for
// reporting purposes (e.g. benchmark/throughput output).
func md4GroupAccelerated() bool { return true }
