//go:build amd64

package main

import (
	"encoding/binary"

	"golang.org/x/sys/cpu"
)

// md5g24AVX2 is the pipelined 3-chain (24-way) AVX2 MD5 core; the assembly
// lives in md5avx2_amd64.s (generated by md5avx2_gen.py, ported from the
// avx2-spike branch). Each chain c hashes 8 lanes at once from a single
// [16][8] word-major, lane-minor message block. out0..out2 receive that
// chain's final [4][8]uint32 state (word w, lane l): word w of chain c's
// lane l digest is out_c[w][l].
//
// msg0..msg2 are declared *uint32 rather than the spike's *[16][8]uint32:
// the assembly only ever does byte-offset loads from the pointer it is
// given, so the pointee type is immaterial to it, and this lets callers
// pass &transposedBatch.words[c*128] directly — that slice is already laid
// out as [chains][16][lanes]uint32, exactly what each msg pointer expects
// — with no marshalling and no unsafe. go vet's asmdecl check compares
// argument sizes and FP offsets, which are identical for any pointer
// regardless of its Go pointee type, so this typing is vet-clean.
//
//go:noescape
func md5g24AVX2(out0, out1, out2 *[4][8]uint32, msg0, msg1, msg2 *uint32, kvec *[64][8]uint32, ivvec *[4][8]uint32, allones *[8]uint32)

// md5g16AVX2 is the sibling N=2 (16-way) core, generated alongside
// md5g24AVX2 by md5avx2_gen.py. It is not used by md5GroupAVX2 (the
// register-budget ceiling of N=3/24-way is strictly more work per call at
// equal per-candidate register cost, per the spike's own report), but it
// is kept and tested since the generator produces it and the committed
// .s must match the generator's output byte-for-byte.
//
//go:noescape
func md5g16AVX2(out0, out1 *[4][8]uint32, msg0, msg1 *uint32, kvec *[64][8]uint32, ivvec *[4][8]uint32, allones *[8]uint32)

// md5AVX2Kvec holds the 64 MD5 round constants, each pre-broadcast into all
// 8 AVX2 lanes so the core can VPADDD a whole vector against it per step.
var md5AVX2Kvec [64][8]uint32

// md5AVX2IVvec holds the MD5 initial state (A,B,C,D), each broadcast into
// all 8 lanes, so every chain starts from the same chaining value.
var md5AVX2IVvec = [4][8]uint32{
	{0x67452301, 0x67452301, 0x67452301, 0x67452301, 0x67452301, 0x67452301, 0x67452301, 0x67452301},
	{0xefcdab89, 0xefcdab89, 0xefcdab89, 0xefcdab89, 0xefcdab89, 0xefcdab89, 0xefcdab89, 0xefcdab89},
	{0x98badcfe, 0x98badcfe, 0x98badcfe, 0x98badcfe, 0x98badcfe, 0x98badcfe, 0x98badcfe, 0x98badcfe},
	{0x10325476, 0x10325476, 0x10325476, 0x10325476, 0x10325476, 0x10325476, 0x10325476, 0x10325476},
}

// md5AVX2Allones is a broadcast [8]uint32 of 0xffffffff, referenced by the
// I round's ~D computation (VPXOR against all-ones, since x86 has no
// single-instruction vector NOT).
var md5AVX2Allones = [8]uint32{0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff}

func init() {
	k := [64]uint32{
		0xd76aa478, 0xe8c7b756, 0x242070db, 0xc1bdceee,
		0xf57c0faf, 0x4787c62a, 0xa8304613, 0xfd469501,
		0x698098d8, 0x8b44f7af, 0xffff5bb1, 0x895cd7be,
		0x6b901122, 0xfd987193, 0xa679438e, 0x49b40821,
		0xf61e2562, 0xc040b340, 0x265e5a51, 0xe9b6c7aa,
		0xd62f105d, 0x02441453, 0xd8a1e681, 0xe7d3fbc8,
		0x21e1cde6, 0xc33707d6, 0xf4d50d87, 0x455a14ed,
		0xa9e3e905, 0xfcefa3f8, 0x676f02d9, 0x8d2a4c8a,
		0xfffa3942, 0x8771f681, 0x6d9d6122, 0xfde5380c,
		0xa4beea44, 0x4bdecfa9, 0xf6bb4b60, 0xbebfbc70,
		0x289b7ec6, 0xeaa127fa, 0xd4ef3085, 0x04881d05,
		0xd9d4d039, 0xe6db99e5, 0x1fa27cf8, 0xc4ac5665,
		0xf4292244, 0x432aff97, 0xab9423a7, 0xfc93a039,
		0x655b59c3, 0x8f0ccc92, 0xffeff47d, 0x85845dd1,
		0x6fa87e4f, 0xfe2ce6e0, 0xa3014314, 0x4e0811a1,
		0xf7537e82, 0xbd3af235, 0x2ad7d2bb, 0xeb86d391,
	}
	for i, v := range k {
		md5AVX2Kvec[i] = [8]uint32{v, v, v, v, v, v, v, v}
	}
}

// avx2Shape is the shape of the AVX2 core: 3 independent 8-lane chains, 24
// candidates per call. Defined identically (build-tag-gated) in both
// md5avx2_amd64.go and md5avx2_generic.go so it is visible regardless of
// GOARCH, matching neonShape's role for the NEON core.
var avx2Shape = vecShape{chains: 3, lanes: 8}

// hasAVX2 reports whether this CPU supports AVX2, so callers can decide
// whether md5GroupAVX2 is safe to dispatch to.
func hasAVX2() bool {
	return cpu.X86.HasAVX2
}

// md5GroupAVX2 hashes all avx2Shape.group() (24) lanes of tb through the
// AVX2 core in one call. tb.words is already [chains][16][lanes]uint32
// flattened (see transposed.go), so chain c's message block is
// &tb.words[c*16*8] — no marshalling.
func md5GroupAVX2(tb *transposedBatch, out [][16]byte) {
	const chainStride = 16 * 8
	var outs [3][4][8]uint32
	md5g24AVX2(
		&outs[0], &outs[1], &outs[2],
		&tb.words[0*chainStride], &tb.words[1*chainStride], &tb.words[2*chainStride],
		&md5AVX2Kvec, &md5AVX2IVvec, &md5AVX2Allones,
	)
	for c := 0; c < 3; c++ {
		for l := 0; l < 8; l++ {
			i := c*8 + l
			for w := 0; w < 4; w++ {
				binary.LittleEndian.PutUint32(out[i][w*4:w*4+4], outs[c][w][l])
			}
		}
	}
}
