//go:build arm64

package main

import "encoding/binary"

// md5g20NEON is the pipelined 5-chain (20-way) NEON MD5 core; the assembly
// lives in md5neon_arm64.s (generated by md5neon_gen.py, ported from the
// Task 5b spike). Each chain c hashes 4 lanes at once from a single [16][4]
// word-major, lane-minor message block. out0..out4 receive that chain's
// final [4][4]uint32 state (word w, lane l): word w of chain c's lane l
// digest is out_c[w][l].
//
// msg0..msg4 are declared *uint32 rather than the spike's *[16][4]uint32:
// the assembly only ever does byte-offset loads from the pointer it is
// given, so the pointee type is immaterial to it, and this lets callers
// pass &transposedBatch.words[c*64] directly — that slice is already laid
// out as [chains][16][lanes]uint32, exactly what each msg pointer expects
// — with no marshalling and no unsafe. go vet's asmdecl check compares
// argument sizes and FP offsets, which are identical for any pointer
// regardless of its Go pointee type, so this typing is vet-clean.
//
//go:noescape
func md5g20NEON(out0, out1, out2, out3, out4 *[4][4]uint32, msg0, msg1, msg2, msg3, msg4 *uint32, kvec *[64][4]uint32, ivvec *[4][4]uint32)

// md5Kvec holds the 64 MD5 round constants, each pre-broadcast into all 4
// NEON lanes so the core can VADD a whole vector against it per step.
var md5Kvec [64][4]uint32

// md5IVvec holds the MD5 initial state (A,B,C,D), each broadcast into all 4
// lanes, so every chain starts from the same chaining value.
var md5IVvec = [4][4]uint32{
	{0x67452301, 0x67452301, 0x67452301, 0x67452301},
	{0xefcdab89, 0xefcdab89, 0xefcdab89, 0xefcdab89},
	{0x98badcfe, 0x98badcfe, 0x98badcfe, 0x98badcfe},
	{0x10325476, 0x10325476, 0x10325476, 0x10325476},
}

func init() {
	k := [64]uint32{
		0xd76aa478, 0xe8c7b756, 0x242070db, 0xc1bdceee,
		0xf57c0faf, 0x4787c62a, 0xa8304613, 0xfd469501,
		0x698098d8, 0x8b44f7af, 0xffff5bb1, 0x895cd7be,
		0x6b901122, 0xfd987193, 0xa679438e, 0x49b40821,
		0xf61e2562, 0xc040b340, 0x265e5a51, 0xe9b6c7aa,
		0xd62f105d, 0x02441453, 0xd8a1e681, 0xe7d3fbc8,
		0x21e1cde6, 0xc33707d6, 0xf4d50d87, 0x455a14ed,
		0xa9e3e905, 0xfcefa3f8, 0x676f02d9, 0x8d2a4c8a,
		0xfffa3942, 0x8771f681, 0x6d9d6122, 0xfde5380c,
		0xa4beea44, 0x4bdecfa9, 0xf6bb4b60, 0xbebfbc70,
		0x289b7ec6, 0xeaa127fa, 0xd4ef3085, 0x04881d05,
		0xd9d4d039, 0xe6db99e5, 0x1fa27cf8, 0xc4ac5665,
		0xf4292244, 0x432aff97, 0xab9423a7, 0xfc93a039,
		0x655b59c3, 0x8f0ccc92, 0xffeff47d, 0x85845dd1,
		0x6fa87e4f, 0xfe2ce6e0, 0xa3014314, 0x4e0811a1,
		0xf7537e82, 0xbd3af235, 0x2ad7d2bb, 0xeb86d391,
	}
	for i, v := range k {
		md5Kvec[i] = [4]uint32{v, v, v, v}
	}
}

// md5Group hashes all neonGroup lanes of tb through the NEON core in one
// call. tb.words is already [neonChains][16][neonLanes]uint32 flattened
// (see transposed.go), so chain c's message block is simply
// &tb.words[c*64] — no marshalling.
func md5Group(tb *transposedBatch, out [][16]byte) {
	var outs [neonChains][4][4]uint32
	md5g20NEON(
		&outs[0], &outs[1], &outs[2], &outs[3], &outs[4],
		&tb.words[0*64], &tb.words[1*64], &tb.words[2*64], &tb.words[3*64], &tb.words[4*64],
		&md5Kvec, &md5IVvec,
	)
	for c := 0; c < neonChains; c++ {
		for l := 0; l < neonLanes; l++ {
			i := c*neonLanes + l
			for w := 0; w < 4; w++ {
				binary.LittleEndian.PutUint32(out[i][w*4:w*4+4], outs[c][w][l])
			}
		}
	}
}
