[metadata]
name = hashsmith-cli
version = 1.2.0
description = Hashsmith CLI for encoding, decoding, hashing, and cracking
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
author = Salih Sefer
url = https://github.com/s4l1hs/Hashsmith

[options]
packages = find:
include_package_data = True
python_requires = >=3.9

[options.package_data]
hashsmith =
    go_hashsmith/go.mod
    go_hashsmith/go.sum
    go_hashsmith/cmd/hashsmith/*.go
    go_hashsmith/cmd/hashsmith/*.txt

[options.entry_points]
console_scripts =
    hashsmith = hashsmith.cli:main
