[metadata]
name = hashsmith-cli
version = 0.1.1
description = Hashsmith CLI for encoding, decoding, hashing, and cracking
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
author = Salih Sefer
url = https://github.com/salihsefer36/Hashsmith

[options]
packages = find:
include_package_data = True
python_requires = >=3.9

[options.entry_points]
console_scripts =
    hashsmith = hashsmith.cli:main
