"""Generator for md5neon_arm64.s — the pipelined 20-way NEON MD5 core.

Ported (trimmed to the single N=5 variant that ships) from the Task 5b
spike's gen3.py (/tmp/md5neon/gen3.py), which also produced 8/12/16-way
siblings that are not needed here — the register budget below is why 5
chains (20-way) is the ceiling on this hardware, so there was never a
reason to ship the smaller variants.

Register budget per chain, after two squeezes:
  - the I round's extra temp is folded away (compute ~d into fR, OR in
    place: `VORR B,fR,fR` is legal ARM aliasing, dest==one src), so f-round
    scratch is a single register (fR) for every round kind.
  - the running "sum" accumulator is folded into the A register itself:
    A's original value is read exactly once (sum = A+f), and A's physical
    register is not touched again until the very end of the same step,
    where it is overwritten with the step's final result anyway (the usual
    role-rotation trick already retires A's register this way). So
    accumulating sum/+K/+M directly into A eliminates a dedicated sum
    register with no lifetime conflict.

That brings each chain down to 6 vector registers: state A,B,C,D (4) +
f-temp (1) + rotate/message-load-temp (1) = 6. Two registers (K-temp,
all-ones) are shared across all chains regardless of N. Total = 6N + 2,
which fits N=5 exactly in 32 registers (30 + 2).

Regenerate with: `python3 md5neon_gen.py` from this directory. Do not
hand-edit md5neon_arm64.s — edit this file and regenerate instead.
"""

import os

K = [
0xd76aa478,0xe8c7b756,0x242070db,0xc1bdceee,
0xf57c0faf,0x4787c62a,0xa8304613,0xfd469501,
0x698098d8,0x8b44f7af,0xffff5bb1,0x895cd7be,
0x6b901122,0xfd987193,0xa679438e,0x49b40821,
0xf61e2562,0xc040b340,0x265e5a51,0xe9b6c7aa,
0xd62f105d,0x02441453,0xd8a1e681,0xe7d3fbc8,
0x21e1cde6,0xc33707d6,0xf4d50d87,0x455a14ed,
0xa9e3e905,0xfcefa3f8,0x676f02d9,0x8d2a4c8a,
0xfffa3942,0x8771f681,0x6d9d6122,0xfde5380c,
0xa4beea44,0x4bdecfa9,0xf6bb4b60,0xbebfbc70,
0x289b7ec6,0xeaa127fa,0xd4ef3085,0x04881d05,
0xd9d4d039,0xe6db99e5,0x1fa27cf8,0xc4ac5665,
0xf4292244,0x432aff97,0xab9423a7,0xfc93a039,
0x655b59c3,0x8f0ccc92,0xffeff47d,0x85845dd1,
0x6fa87e4f,0xfe2ce6e0,0xa3014314,0x4e0811a1,
0xf7537e82,0xbd3af235,0x2ad7d2bb,0xeb86d391,
]
S = [7,12,17,22]*4 + [5,9,14,20]*4 + [4,11,16,23]*4 + [6,10,15,21]*4

def msgidx(step):
    i = step % 16
    if step < 16:
        return i
    elif step < 32:
        return (5*i+1) % 16
    elif step < 48:
        return (3*i+5) % 16
    else:
        return (7*i) % 16

def func_kind(step):
    if step < 16: return 'F'
    if step < 32: return 'G'
    if step < 48: return 'H'
    return 'I'

def chain_block(step, regs, fR, rotR, allonesR, kR, msgBaseR, addrR):
    A, B, C, D = regs
    kind = func_kind(step)
    mi = msgidx(step)
    s = S[step]
    off = mi * 16
    lines = []
    lines.append('\t// step %d %s msg=%s(off=%d) s=%d A=%s' % (step, kind, msgBaseR, off, s, A))
    lines.append('\tADD $%d, %s, %s' % (off, msgBaseR, addrR))
    lines.append('\tVLD1 (%s), [%s.S4]' % (addrR, rotR))
    if kind == 'F':
        lines.append('\tVMOV %s.B16, %s.B16' % (B, fR))
        lines.append('\tVBSL %s.B16, %s.B16, %s.B16' % (D, C, fR))
    elif kind == 'G':
        lines.append('\tVMOV %s.B16, %s.B16' % (D, fR))
        lines.append('\tVBSL %s.B16, %s.B16, %s.B16' % (C, B, fR))
    elif kind == 'H':
        lines.append('\tVEOR %s.B16, %s.B16, %s.B16' % (B, C, fR))
        lines.append('\tVEOR %s.B16, %s.B16, %s.B16' % (fR, D, fR))
    else:  # I: fR = ~D, then fR = B|fR (in place), then fR = fR^C
        lines.append('\tVEOR %s.B16, %s.B16, %s.B16' % (D, allonesR, fR))
        lines.append('\tVORR %s.B16, %s.B16, %s.B16' % (B, fR, fR))
        lines.append('\tVEOR %s.B16, %s.B16, %s.B16' % (fR, C, fR))
    # A = A + f   (accumulate in place; old A value is dead after this read)
    lines.append('\tVADD %s.S4, %s.S4, %s.S4' % (A, fR, A))
    # A += K
    lines.append('\tVADD %s.S4, %s.S4, %s.S4' % (A, kR, A))
    # A += M   (rotR currently holds the freshly loaded message word)
    lines.append('\tVADD %s.S4, %s.S4, %s.S4' % (A, rotR, A))
    # rotate left by s (rotR reused; message value already consumed)
    lines.append('\tVSHL $%d, %s.S4, %s.S4' % (s, A, rotR))
    lines.append('\tVSRI $%d, %s.S4, %s.S4' % (32 - s, A, rotR))
    # newB = B + rotated, written into A's register (this step's retiree)
    lines.append('\tVADD %s.S4, %s.S4, %s.S4' % (B, rotR, A))
    lines.append('')
    return lines, [D, A, B, C]

HEADER = '''// Code generated by md5neon_gen.py. DO NOT EDIT BY HAND — edit md5neon_gen.py
// and regenerate with `python3 md5neon_gen.py` from this directory.
//
// Ported from the Task 5b spike (/tmp/md5neon/gen3.py, generate(5,
// "md5g20NEON", ...)), the 5-chain (20-way) generic register-squeezed core:
// five independent 4-way NEON MD5 chains, software-pipelined so the
// out-of-order core overlaps their serial-dependency latency (MD5's 64
// steps are one long dependency chain per message, so throughput comes
// from independent work in flight, not from one faster hash). Register
// budget is 6 vector regs/chain (state A,B,C,D + f-temp + rotate-temp) + 2
// shared (K-temp, all-ones) = 6*5+2 = 32, exactly filling the register
// file — this is why 5 chains (20-way) and not more.
//
// The instruction body below is unchanged from the spike; only this header
// and the msg parameter typing in the comment differ (the production Go
// declaration in md5neon_arm64.go takes msg0..msg4 as *uint32, pointing
// directly at transposedBatch.words[c*64], rather than the spike's
// *[16][4]uint32 — the assembly only ever does byte-offset loads from that
// address, so the pointee type is immaterial to it; go vet's asmdecl check
// only compares argument sizes/offsets, which are identical for any
// pointer).
#include "textflag.h"

// func %(funcname)s(%(outlist)s *[4][4]uint32, %(msglist)s *uint32, kvec *[64][4]uint32, ivvec *[4][4]uint32)
TEXT ·%(funcname)s(SB), NOSPLIT, $0-%(argsz)d
%(prologue)s

%(load_state)s

\tVMOVI $0xff, V25.B16

'''

def generate(n, funcname, outpath):
    pool = [i for i in range(32) if i not in (20, 25)]
    assert n * 6 <= len(pool), 'too many chains for register budget'

    chain_regs = []   # per chain: (state[4], fR, rotR)
    for c in range(n):
        base = pool[c*6:(c+1)*6]
        state = ['V%d' % r for r in base[0:4]]
        fR = 'V%d' % base[4]
        rotR = 'V%d' % base[5]
        chain_regs.append([state, fR, rotR])

    # GPRs
    out_regs = ['R%d' % i for i in range(n)]
    msg_regs = ['R%d' % (n + i) for i in range(n)]
    kvec_reg = 'R%d' % (2 * n)
    iv_reg = 'R%d' % (2 * n + 1)
    addr_regs = ['R%d' % (2 * n + 2 + i) for i in range(n)]
    ivaddr_reg = 'R%d' % (2 * n + 2 + n)

    lines = []
    for step in range(64):
        lines.append('\tVLD1.P 16(%s), [V20.S4] // K[%d], shared by all %d chains' % (kvec_reg, step, n))
        for c in range(n):
            state, fR, rotR = chain_regs[c]
            blk, newstate = chain_block(step, state, fR, rotR, 'V25', 'V20',
                                         msg_regs[c], addr_regs[c])
            lines += blk
            chain_regs[c][0] = newstate

    body = '\n'.join(lines)

    argsz = 8 * (n + n + 1 + 1)  # out ptrs + msg ptrs + kvec + ivvec
    prologue = []
    off = 0
    for i in range(n):
        prologue.append('\tMOVD out%d+%d(FP), %s' % (i, off, out_regs[i])); off += 8
    for i in range(n):
        prologue.append('\tMOVD msg%d+%d(FP), %s' % (i, off, msg_regs[i])); off += 8
    prologue.append('\tMOVD kvec+%d(FP), %s' % (off, kvec_reg)); off += 8
    prologue.append('\tMOVD ivvec+%d(FP), %s' % (off, iv_reg)); off += 8

    # Chain state registers are not guaranteed contiguous (they're carved
    # out of a 30-register pool with two holes at V20/V25), and ARM64's
    # multi-register LD1/ST1 list form requires contiguous register
    # numbers. So IV load-in and final store both go word-by-word with a
    # single-register VLD1/VST1 and a computed address, rather than a
    # 4-register list - negligible cost since it happens once per call,
    # not once per step.
    load_state = []
    for w in range(4):
        load_state.append('\tADD $%d, %s, %s' % (w * 16, iv_reg, ivaddr_reg))
        for c in range(n):
            base = pool[c*6:(c+1)*6]
            r = base[w]
            load_state.append('\tVLD1 (%s), [V%d.S4]' % (ivaddr_reg, r))

    header = HEADER % {
        'funcname': funcname,
        'outlist': ', '.join('out%d' % i for i in range(n)),
        'msglist': ', '.join('msg%d' % i for i in range(n)),
        'argsz': argsz,
        'prologue': '\n'.join(prologue),
        'load_state': '\n'.join(load_state),
    }

    # Footer: add the initial MD5 state back into each chain's final state
    # (the classic "add chaining value" step). We reload the IV from its
    # (untouched, read-only) memory location one word at a time into the
    # single now-free V20 register - K and the all-ones constant are no
    # longer needed once the 64-step loop is done - rather than reserving
    # dedicated registers for it across the whole run. This is 4 tiny loads
    # total, off the critical path, regardless of how many chains N is.
    footer_lines = []
    for w in range(4):
        footer_lines.append('\tADD $%d, %s, %s' % (w * 16, iv_reg, ivaddr_reg))
        footer_lines.append('\tVLD1 (%s), [V20.S4]' % ivaddr_reg)
        for c in range(n):
            base = pool[c*6:(c+1)*6]
            r = base[w]
            footer_lines.append('\tVADD V%d.S4, V20.S4, V%d.S4' % (r, r))
    for c in range(n):
        base = pool[c*6:(c+1)*6]
        for w in range(4):
            r = base[w]
            footer_lines.append('\tADD $%d, %s, %s' % (w * 16, out_regs[c], ivaddr_reg))
            footer_lines.append('\tVST1 [V%d.S4], (%s)' % (r, ivaddr_reg))
    footer_lines.append('\tRET')

    with open(outpath, 'w') as f:
        f.write(header)
        f.write(body)
        f.write('\n'.join(footer_lines))
        f.write('\n')
    print('generated', outpath, 'n=', n, 'vregs/chain=6 total=', 6*n+2)

if __name__ == '__main__':
    outdir = os.path.dirname(os.path.abspath(__file__))
    generate(5, 'md5g20NEON', os.path.join(outdir, 'md5neon_arm64.s'))
