package smith

// Differential compatibility vectors against hashcat's rule engine.
//
// Every expectation in this table was produced by running the real hashcat
// binary (7.1.2) as an oracle:
//
//	printf '<rule>\n' > r.rule && hashcat --stdout -r r.rule words.txt
//
// They are embedded rather than shelled out to so CI needs no hashcat install;
// scripts/rules-oracle.sh regenerates them against a local hashcat and fails
// if the committed table has drifted.
//
// Two classes of behaviour are pinned here:
//
//   - the operators hashcat has that Hashsmith did not (O + - . , L R E e);
//   - out-of-range position handling. hashcat leaves a word UNCHANGED when a
//     position operand lies past its end; Hashsmith used to reject the word
//     outright, which silently shrank the searched keyspace for any rule file
//     using them. Rejecting is the dangerous direction: it turns "not found"
//     into a lie.
//
// Rule bytes and expected candidates are raw bytes, not runes: hashcat mangles
// byte strings, and shifts like L0 legitimately produce bytes outside ASCII
// that are not valid UTF-8 on their own.

import "testing"

// hashcatVector is one (rule, input, expected-output) triple from the oracle.
type hashcatVector struct{ rule, in, want string }

var hashcatRuleVectors = []hashcatVector{
	{"O12", "hello", "hlo"},
	{"O12", "password", "psword"},
	{"O12", "Abc123", "A123"},
	{"O12", "hi", "hi"},
	{"O12", "foo bar", "f bar"},
	{"O12", "hELLO wORLD", "hLO wORLD"},
	{"O12", "abcdef", "adef"},
	{"O12", "a", "a"},
	{"O01", "hello", "ello"},
	{"O01", "password", "assword"},
	{"O01", "Abc123", "bc123"},
	{"O01", "hi", "i"},
	{"O01", "foo bar", "oo bar"},
	{"O01", "hELLO wORLD", "ELLO wORLD"},
	{"O01", "abcdef", "bcdef"},
	{"O01", "a", ""},
	{"O24", "hello", "hello"},
	{"O24", "password", "pard"},
	{"O24", "Abc123", "Ab"},
	{"O24", "hi", "hi"},
	{"O24", "foo bar", "for"},
	{"O24", "hELLO wORLD", "hEwORLD"},
	{"O24", "abcdef", "ab"},
	{"O24", "a", "a"},
	{"O99", "hello", "hello"},
	{"O99", "password", "password"},
	{"O99", "Abc123", "Abc123"},
	{"O99", "hi", "hi"},
	{"O99", "foo bar", "foo bar"},
	{"O99", "hELLO wORLD", "hELLO wORLD"},
	{"O99", "abcdef", "abcdef"},
	{"O99", "a", "a"},
	{"O0A", "hello", "hello"},
	{"O0A", "password", "password"},
	{"O0A", "Abc123", "Abc123"},
	{"O0A", "hi", "hi"},
	{"O0A", "foo bar", "foo bar"},
	{"O0A", "hELLO wORLD", "D"},
	{"O0A", "abcdef", "abcdef"},
	{"O0A", "a", "a"},
	{"O21", "hello", "helo"},
	{"O21", "password", "pasword"},
	{"O21", "Abc123", "Ab123"},
	{"O21", "hi", "hi"},
	{"O21", "foo bar", "fo bar"},
	{"O21", "hELLO wORLD", "hELO wORLD"},
	{"O21", "abcdef", "abdef"},
	{"O21", "a", "a"},
	{"+0", "hello", "iello"},
	{"+0", "password", "qassword"},
	{"+0", "Abc123", "Bbc123"},
	{"+0", "hi", "ii"},
	{"+0", "foo bar", "goo bar"},
	{"+0", "hELLO wORLD", "iELLO wORLD"},
	{"+0", "abcdef", "bbcdef"},
	{"+0", "a", "b"},
	{"+1", "hello", "hfllo"},
	{"+1", "password", "pbssword"},
	{"+1", "Abc123", "Acc123"},
	{"+1", "hi", "hj"},
	{"+1", "foo bar", "fpo bar"},
	{"+1", "hELLO wORLD", "hFLLO wORLD"},
	{"+1", "abcdef", "accdef"},
	{"+1", "a", "a"},
	{"+5", "hello", "hello"},
	{"+5", "password", "passwprd"},
	{"+5", "Abc123", "Abc124"},
	{"+5", "hi", "hi"},
	{"+5", "foo bar", "foo bbr"},
	{"+5", "hELLO wORLD", "hELLO!wORLD"},
	{"+5", "abcdef", "abcdeg"},
	{"+5", "a", "a"},
	{"+9", "hello", "hello"},
	{"+9", "password", "password"},
	{"+9", "Abc123", "Abc123"},
	{"+9", "hi", "hi"},
	{"+9", "foo bar", "foo bar"},
	{"+9", "hELLO wORLD", "hELLO wORMD"},
	{"+9", "abcdef", "abcdef"},
	{"+9", "a", "a"},
	{"-0", "hello", "gello"},
	{"-0", "password", "oassword"},
	{"-0", "Abc123", "@bc123"},
	{"-0", "hi", "gi"},
	{"-0", "foo bar", "eoo bar"},
	{"-0", "hELLO wORLD", "gELLO wORLD"},
	{"-0", "abcdef", "`bcdef"},
	{"-0", "a", "`"},
	{"-1", "hello", "hdllo"},
	{"-1", "password", "p`ssword"},
	{"-1", "Abc123", "Aac123"},
	{"-1", "hi", "hh"},
	{"-1", "foo bar", "fno bar"},
	{"-1", "hELLO wORLD", "hDLLO wORLD"},
	{"-1", "abcdef", "aacdef"},
	{"-1", "a", "a"},
	{"-5", "hello", "hello"},
	{"-5", "password", "passwnrd"},
	{"-5", "Abc123", "Abc122"},
	{"-5", "hi", "hi"},
	{"-5", "foo bar", "foo b`r"},
	{"-5", "hELLO wORLD", "hELLO\x1fwORLD"},
	{"-5", "abcdef", "abcdee"},
	{"-5", "a", "a"},
	{"-9", "hello", "hello"},
	{"-9", "password", "password"},
	{"-9", "Abc123", "Abc123"},
	{"-9", "hi", "hi"},
	{"-9", "foo bar", "foo bar"},
	{"-9", "hELLO wORLD", "hELLO wORKD"},
	{"-9", "abcdef", "abcdef"},
	{"-9", "a", "a"},
	{".0", "hello", "eello"},
	{".0", "password", "aassword"},
	{".0", "Abc123", "bbc123"},
	{".0", "hi", "ii"},
	{".0", "foo bar", "ooo bar"},
	{".0", "hELLO wORLD", "EELLO wORLD"},
	{".0", "abcdef", "bbcdef"},
	{".0", "a", "a"},
	{".1", "hello", "hlllo"},
	{".1", "password", "psssword"},
	{".1", "Abc123", "Acc123"},
	{".1", "hi", "hi"},
	{".1", "foo bar", "foo bar"},
	{".1", "hELLO wORLD", "hLLLO wORLD"},
	{".1", "abcdef", "accdef"},
	{".1", "a", "a"},
	{".4", "hello", "hello"},
	{".4", "password", "passoord"},
	{".4", "Abc123", "Abc133"},
	{".4", "hi", "hi"},
	{".4", "foo bar", "foo aar"},
	{".4", "hELLO wORLD", "hELL  wORLD"},
	{".4", "abcdef", "abcdff"},
	{".4", "a", "a"},
	{".9", "hello", "hello"},
	{".9", "password", "password"},
	{".9", "Abc123", "Abc123"},
	{".9", "hi", "hi"},
	{".9", "foo bar", "foo bar"},
	{".9", "hELLO wORLD", "hELLO wORDD"},
	{".9", "abcdef", "abcdef"},
	{".9", "a", "a"},
	{",1", "hello", "hhllo"},
	{",1", "password", "ppssword"},
	{",1", "Abc123", "AAc123"},
	{",1", "hi", "hh"},
	{",1", "foo bar", "ffo bar"},
	{",1", "hELLO wORLD", "hhLLO wORLD"},
	{",1", "abcdef", "aacdef"},
	{",1", "a", "a"},
	{",2", "hello", "heelo"},
	{",2", "password", "paasword"},
	{",2", "Abc123", "Abb123"},
	{",2", "hi", "hi"},
	{",2", "foo bar", "foo bar"},
	{",2", "hELLO wORLD", "hEELO wORLD"},
	{",2", "abcdef", "abbdef"},
	{",2", "a", "a"},
	{",5", "hello", "hello"},
	{",5", "password", "passwwrd"},
	{",5", "Abc123", "Abc122"},
	{",5", "hi", "hi"},
	{",5", "foo bar", "foo bbr"},
	{",5", "hELLO wORLD", "hELLOOwORLD"},
	{",5", "abcdef", "abcdee"},
	{",5", "a", "a"},
	{",9", "hello", "hello"},
	{",9", "password", "password"},
	{",9", "Abc123", "Abc123"},
	{",9", "hi", "hi"},
	{",9", "foo bar", "foo bar"},
	{",9", "hELLO wORLD", "hELLO wORRD"},
	{",9", "abcdef", "abcdef"},
	{",9", "a", "a"},
	{"L0", "hello", "\xd0ello"},
	{"L0", "password", "\xe0assword"},
	{"L0", "Abc123", "\x82bc123"},
	{"L0", "hi", "\xd0i"},
	{"L0", "foo bar", "\xccoo bar"},
	{"L0", "hELLO wORLD", "\xd0ELLO wORLD"},
	{"L0", "abcdef", "\xc2bcdef"},
	{"L0", "a", "\xc2"},
	{"L1", "hello", "h\xcallo"},
	{"L1", "password", "p\xc2ssword"},
	{"L1", "Abc123", "A\xc4c123"},
	{"L1", "hi", "h\xd2"},
	{"L1", "foo bar", "f\xdeo bar"},
	{"L1", "hELLO wORLD", "h\x8aLLO wORLD"},
	{"L1", "abcdef", "a\xc4cdef"},
	{"L1", "a", "a"},
	{"R0", "hello", "4ello"},
	{"R0", "password", "8assword"},
	{"R0", "Abc123", " bc123"},
	{"R0", "hi", "4i"},
	{"R0", "foo bar", "3oo bar"},
	{"R0", "hELLO wORLD", "4ELLO wORLD"},
	{"R0", "abcdef", "0bcdef"},
	{"R0", "a", "0"},
	{"R1", "hello", "h2llo"},
	{"R1", "password", "p0ssword"},
	{"R1", "Abc123", "A1c123"},
	{"R1", "hi", "h4"},
	{"R1", "foo bar", "f7o bar"},
	{"R1", "hELLO wORLD", "h\"LLO wORLD"},
	{"R1", "abcdef", "a1cdef"},
	{"R1", "a", "a"},
	{"R5", "hello", "hello"},
	{"R5", "password", "passw7rd"},
	{"R5", "Abc123", "Abc12\x19"},
	{"R5", "hi", "hi"},
	{"R5", "foo bar", "foo b0r"},
	{"R5", "hELLO wORLD", "hELLO\x10wORLD"},
	{"R5", "abcdef", "abcde3"},
	{"R5", "a", "a"},
	{"R9", "hello", "hello"},
	{"R9", "password", "password"},
	{"R9", "Abc123", "Abc123"},
	{"R9", "hi", "hi"},
	{"R9", "foo bar", "foo bar"},
	{"R9", "hELLO wORLD", "hELLO wOR&D"},
	{"R9", "abcdef", "abcdef"},
	{"R9", "a", "a"},
	{"E", "hello", "Hello"},
	{"E", "password", "Password"},
	{"E", "Abc123", "Abc123"},
	{"E", "hi", "Hi"},
	{"E", "foo bar", "Foo Bar"},
	{"E", "hELLO wORLD", "Hello World"},
	{"E", "abcdef", "Abcdef"},
	{"E", "a", "A"},
	{"e-", "hello", "Hello"},
	{"e-", "password", "Password"},
	{"e-", "Abc123", "Abc123"},
	{"e-", "hi", "Hi"},
	{"e-", "foo bar", "Foo bar"},
	{"e-", "hELLO wORLD", "Hello world"},
	{"e-", "abcdef", "Abcdef"},
	{"e-", "a", "A"},
	{"e_", "hello", "Hello"},
	{"e_", "password", "Password"},
	{"e_", "Abc123", "Abc123"},
	{"e_", "hi", "Hi"},
	{"e_", "foo bar", "Foo bar"},
	{"e_", "hELLO wORLD", "Hello world"},
	{"e_", "abcdef", "Abcdef"},
	{"e_", "a", "A"},
	{"D0", "hello", "ello"},
	{"D0", "password", "assword"},
	{"D0", "Abc123", "bc123"},
	{"D0", "hi", "i"},
	{"D0", "foo bar", "oo bar"},
	{"D0", "hELLO wORLD", "ELLO wORLD"},
	{"D0", "abcdef", "bcdef"},
	{"D0", "a", ""},
	{"D1", "hello", "hllo"},
	{"D1", "password", "pssword"},
	{"D1", "Abc123", "Ac123"},
	{"D1", "hi", "h"},
	{"D1", "foo bar", "fo bar"},
	{"D1", "hELLO wORLD", "hLLO wORLD"},
	{"D1", "abcdef", "acdef"},
	{"D1", "a", "a"},
	{"D5", "hello", "hello"},
	{"D5", "password", "passwrd"},
	{"D5", "Abc123", "Abc12"},
	{"D5", "hi", "hi"},
	{"D5", "foo bar", "foo br"},
	{"D5", "hELLO wORLD", "hELLOwORLD"},
	{"D5", "abcdef", "abcde"},
	{"D5", "a", "a"},
	{"D9", "hello", "hello"},
	{"D9", "password", "password"},
	{"D9", "Abc123", "Abc123"},
	{"D9", "hi", "hi"},
	{"D9", "foo bar", "foo bar"},
	{"D9", "hELLO wORLD", "hELLO wORD"},
	{"D9", "abcdef", "abcdef"},
	{"D9", "a", "a"},
	{"T0", "hello", "Hello"},
	{"T0", "password", "Password"},
	{"T0", "Abc123", "abc123"},
	{"T0", "hi", "Hi"},
	{"T0", "foo bar", "Foo bar"},
	{"T0", "hELLO wORLD", "HELLO wORLD"},
	{"T0", "abcdef", "Abcdef"},
	{"T0", "a", "A"},
	{"T1", "hello", "hEllo"},
	{"T1", "password", "pAssword"},
	{"T1", "Abc123", "ABc123"},
	{"T1", "hi", "hI"},
	{"T1", "foo bar", "fOo bar"},
	{"T1", "hELLO wORLD", "heLLO wORLD"},
	{"T1", "abcdef", "aBcdef"},
	{"T1", "a", "a"},
	{"T5", "hello", "hello"},
	{"T5", "password", "passwOrd"},
	{"T5", "Abc123", "Abc123"},
	{"T5", "hi", "hi"},
	{"T5", "foo bar", "foo bAr"},
	{"T5", "hELLO wORLD", "hELLO wORLD"},
	{"T5", "abcdef", "abcdeF"},
	{"T5", "a", "a"},
	{"T9", "hello", "hello"},
	{"T9", "password", "password"},
	{"T9", "Abc123", "Abc123"},
	{"T9", "hi", "hi"},
	{"T9", "foo bar", "foo bar"},
	{"T9", "hELLO wORLD", "hELLO wORlD"},
	{"T9", "abcdef", "abcdef"},
	{"T9", "a", "a"},
	{"o0z", "hello", "zello"},
	{"o0z", "password", "zassword"},
	{"o0z", "Abc123", "zbc123"},
	{"o0z", "hi", "zi"},
	{"o0z", "foo bar", "zoo bar"},
	{"o0z", "hELLO wORLD", "zELLO wORLD"},
	{"o0z", "abcdef", "zbcdef"},
	{"o0z", "a", "z"},
	{"o2z", "hello", "hezlo"},
	{"o2z", "password", "pazsword"},
	{"o2z", "Abc123", "Abz123"},
	{"o2z", "hi", "hi"},
	{"o2z", "foo bar", "foz bar"},
	{"o2z", "hELLO wORLD", "hEzLO wORLD"},
	{"o2z", "abcdef", "abzdef"},
	{"o2z", "a", "a"},
	{"o5z", "hello", "hello"},
	{"o5z", "password", "passwzrd"},
	{"o5z", "Abc123", "Abc12z"},
	{"o5z", "hi", "hi"},
	{"o5z", "foo bar", "foo bzr"},
	{"o5z", "hELLO wORLD", "hELLOzwORLD"},
	{"o5z", "abcdef", "abcdez"},
	{"o5z", "a", "a"},
	{"o9z", "hello", "hello"},
	{"o9z", "password", "password"},
	{"o9z", "Abc123", "Abc123"},
	{"o9z", "hi", "hi"},
	{"o9z", "foo bar", "foo bar"},
	{"o9z", "hELLO wORLD", "hELLO wORzD"},
	{"o9z", "abcdef", "abcdef"},
	{"o9z", "a", "a"},
	{"i0z", "hello", "zhello"},
	{"i0z", "password", "zpassword"},
	{"i0z", "Abc123", "zAbc123"},
	{"i0z", "hi", "zhi"},
	{"i0z", "foo bar", "zfoo bar"},
	{"i0z", "hELLO wORLD", "zhELLO wORLD"},
	{"i0z", "abcdef", "zabcdef"},
	{"i0z", "a", "za"},
	{"i2z", "hello", "hezllo"},
	{"i2z", "password", "pazssword"},
	{"i2z", "Abc123", "Abzc123"},
	{"i2z", "hi", "hiz"},
	{"i2z", "foo bar", "fozo bar"},
	{"i2z", "hELLO wORLD", "hEzLLO wORLD"},
	{"i2z", "abcdef", "abzcdef"},
	{"i2z", "a", "a"},
	{"i5z", "hello", "helloz"},
	{"i5z", "password", "passwzord"},
	{"i5z", "Abc123", "Abc12z3"},
	{"i5z", "hi", "hi"},
	{"i5z", "foo bar", "foo bzar"},
	{"i5z", "hELLO wORLD", "hELLOz wORLD"},
	{"i5z", "abcdef", "abcdezf"},
	{"i5z", "a", "a"},
	{"i9z", "hello", "hello"},
	{"i9z", "password", "password"},
	{"i9z", "Abc123", "Abc123"},
	{"i9z", "hi", "hi"},
	{"i9z", "foo bar", "foo bar"},
	{"i9z", "hELLO wORLD", "hELLO wORzLD"},
	{"i9z", "abcdef", "abcdef"},
	{"i9z", "a", "a"},
	{"x02", "hello", "he"},
	{"x02", "password", "pa"},
	{"x02", "Abc123", "Ab"},
	{"x02", "hi", "hi"},
	{"x02", "foo bar", "fo"},
	{"x02", "hELLO wORLD", "hE"},
	{"x02", "abcdef", "ab"},
	{"x02", "a", "a"},
	{"x12", "hello", "el"},
	{"x12", "password", "as"},
	{"x12", "Abc123", "bc"},
	{"x12", "hi", "hi"},
	{"x12", "foo bar", "oo"},
	{"x12", "hELLO wORLD", "EL"},
	{"x12", "abcdef", "bc"},
	{"x12", "a", "a"},
	{"x25", "hello", "hello"},
	{"x25", "password", "sswor"},
	{"x25", "Abc123", "Abc123"},
	{"x25", "hi", "hi"},
	{"x25", "foo bar", "o bar"},
	{"x25", "hELLO wORLD", "LLO w"},
	{"x25", "abcdef", "abcdef"},
	{"x25", "a", "a"},
	{"x29", "hello", "hello"},
	{"x29", "password", "password"},
	{"x29", "Abc123", "Abc123"},
	{"x29", "hi", "hi"},
	{"x29", "foo bar", "foo bar"},
	{"x29", "hELLO wORLD", "LLO wORLD"},
	{"x29", "abcdef", "abcdef"},
	{"x29", "a", "a"},
	{"*01", "hello", "ehllo"},
	{"*01", "password", "apssword"},
	{"*01", "Abc123", "bAc123"},
	{"*01", "hi", "ih"},
	{"*01", "foo bar", "ofo bar"},
	{"*01", "hELLO wORLD", "EhLLO wORLD"},
	{"*01", "abcdef", "bacdef"},
	{"*01", "a", "a"},
	{"*04", "hello", "oellh"},
	{"*04", "password", "wasspord"},
	{"*04", "Abc123", "2bc1A3"},
	{"*04", "hi", "hi"},
	{"*04", "foo bar", "boo far"},
	{"*04", "hELLO wORLD", "OELLh wORLD"},
	{"*04", "abcdef", "ebcdaf"},
	{"*04", "a", "a"},
	{"*09", "hello", "hello"},
	{"*09", "password", "password"},
	{"*09", "Abc123", "Abc123"},
	{"*09", "hi", "hi"},
	{"*09", "foo bar", "foo bar"},
	{"*09", "hELLO wORLD", "LELLO wORhD"},
	{"*09", "abcdef", "abcdef"},
	{"*09", "a", "a"},
	{"z1", "hello", "hhello"},
	{"z1", "password", "ppassword"},
	{"z1", "Abc123", "AAbc123"},
	{"z1", "hi", "hhi"},
	{"z1", "foo bar", "ffoo bar"},
	{"z1", "hELLO wORLD", "hhELLO wORLD"},
	{"z1", "abcdef", "aabcdef"},
	{"z1", "a", "aa"},
	{"z9", "hello", "hhhhhhhhhhello"},
	{"z9", "password", "ppppppppppassword"},
	{"z9", "Abc123", "AAAAAAAAAAbc123"},
	{"z9", "hi", "hhhhhhhhhhi"},
	{"z9", "foo bar", "ffffffffffoo bar"},
	{"z9", "hELLO wORLD", "hhhhhhhhhhELLO wORLD"},
	{"z9", "abcdef", "aaaaaaaaaabcdef"},
	{"z9", "a", "aaaaaaaaaa"},
	{"Z1", "hello", "helloo"},
	{"Z1", "password", "passwordd"},
	{"Z1", "Abc123", "Abc1233"},
	{"Z1", "hi", "hii"},
	{"Z1", "foo bar", "foo barr"},
	{"Z1", "hELLO wORLD", "hELLO wORLDD"},
	{"Z1", "abcdef", "abcdeff"},
	{"Z1", "a", "aa"},
	{"Z9", "hello", "helloooooooooo"},
	{"Z9", "password", "passwordddddddddd"},
	{"Z9", "Abc123", "Abc123333333333"},
	{"Z9", "hi", "hiiiiiiiiii"},
	{"Z9", "foo bar", "foo barrrrrrrrrr"},
	{"Z9", "hELLO wORLD", "hELLO wORLDDDDDDDDDD"},
	{"Z9", "abcdef", "abcdeffffffffff"},
	{"Z9", "a", "aaaaaaaaaa"},
	{"y1", "hello", "hhello"},
	{"y1", "password", "ppassword"},
	{"y1", "Abc123", "AAbc123"},
	{"y1", "hi", "hhi"},
	{"y1", "foo bar", "ffoo bar"},
	{"y1", "hELLO wORLD", "hhELLO wORLD"},
	{"y1", "abcdef", "aabcdef"},
	{"y1", "a", "aa"},
	{"y2", "hello", "hehello"},
	{"y2", "password", "papassword"},
	{"y2", "Abc123", "AbAbc123"},
	{"y2", "hi", "hihi"},
	{"y2", "foo bar", "fofoo bar"},
	{"y2", "hELLO wORLD", "hEhELLO wORLD"},
	{"y2", "abcdef", "ababcdef"},
	{"y2", "a", "a"},
	{"y3", "hello", "helhello"},
	{"y3", "password", "paspassword"},
	{"y3", "Abc123", "AbcAbc123"},
	{"y3", "hi", "hi"},
	{"y3", "foo bar", "foofoo bar"},
	{"y3", "hELLO wORLD", "hELhELLO wORLD"},
	{"y3", "abcdef", "abcabcdef"},
	{"y3", "a", "a"},
	{"y9", "hello", "hello"},
	{"y9", "password", "password"},
	{"y9", "Abc123", "Abc123"},
	{"y9", "hi", "hi"},
	{"y9", "foo bar", "foo bar"},
	{"y9", "hELLO wORLD", "hELLO wORhELLO wORLD"},
	{"y9", "abcdef", "abcdef"},
	{"y9", "a", "a"},
	{"Y1", "hello", "helloo"},
	{"Y1", "password", "passwordd"},
	{"Y1", "Abc123", "Abc1233"},
	{"Y1", "hi", "hii"},
	{"Y1", "foo bar", "foo barr"},
	{"Y1", "hELLO wORLD", "hELLO wORLDD"},
	{"Y1", "abcdef", "abcdeff"},
	{"Y1", "a", "aa"},
	{"Y2", "hello", "hellolo"},
	{"Y2", "password", "passwordrd"},
	{"Y2", "Abc123", "Abc12323"},
	{"Y2", "hi", "hihi"},
	{"Y2", "foo bar", "foo barar"},
	{"Y2", "hELLO wORLD", "hELLO wORLDLD"},
	{"Y2", "abcdef", "abcdefef"},
	{"Y2", "a", "a"},
	{"Y3", "hello", "hellollo"},
	{"Y3", "password", "passwordord"},
	{"Y3", "Abc123", "Abc123123"},
	{"Y3", "hi", "hi"},
	{"Y3", "foo bar", "foo barbar"},
	{"Y3", "hELLO wORLD", "hELLO wORLDRLD"},
	{"Y3", "abcdef", "abcdefdef"},
	{"Y3", "a", "a"},
	{"Y9", "hello", "hello"},
	{"Y9", "password", "password"},
	{"Y9", "Abc123", "Abc123"},
	{"Y9", "hi", "hi"},
	{"Y9", "foo bar", "foo bar"},
	{"Y9", "hELLO wORLD", "hELLO wORLDLLO wORLD"},
	{"Y9", "abcdef", "abcdef"},
	{"Y9", "a", "a"},
}

// TestHashcatRuleCompat replays every oracle vector through the rule engine.
// A rule that hashcat applies must compile, must not reject, and must produce
// hashcat's exact bytes.
func TestHashcatRuleCompat(t *testing.T) {
	for _, v := range hashcatRuleVectors {
		p, err := compileRuleLine(v.rule)
		if err != nil {
			t.Errorf("rule %q: compile error: %v", v.rule, err)
			continue
		}
		got, ok := p.apply(v.in)
		if !ok {
			t.Errorf("rule %q on %q: rejected, hashcat produces %q", v.rule, v.in, v.want)
			continue
		}
		if got != v.want {
			t.Errorf("rule %q on %q: got %q, hashcat produces %q", v.rule, v.in, got, v.want)
		}
	}
}

// TestHashcatRuleLengthCap pins hashcat's password-buffer limit: a command
// whose result would reach 256 bytes is skipped and leaves the word as it was,
// rather than producing the oversized candidate or rejecting the whole rule.
//
// Oracle (hashcat 7.1.2), with words of 'a' repeated:
//
//	len 127 + "p1" -> 254   len 128 + "p1" -> 128 (skipped)
//	len 254 + "$a" -> 255   len 255 + "$a" -> 255 (skipped)
//	"z3 p4 p4" on "password" -> 55, not 275
//	"p9 p9"    on "password" -> 80, not 800
func TestHashcatRuleLengthCap(t *testing.T) {
	rep := func(n int) string {
		b := make([]byte, n)
		for i := range b {
			b[i] = 'a'
		}
		return string(b)
	}
	cases := []struct {
		rule, in string
		wantLen  int
	}{
		{"p1", rep(127), 254}, // fits: 254 < 256
		{"p1", rep(128), 128}, // would be 256 — skipped, word unchanged
		{"$a", rep(254), 255}, // fits: 255 < 256
		{"$a", rep(255), 255}, // would be 256 — skipped, word unchanged
		{"z3 p4 p4", "password", 55},
		{"p9 p9", "password", 80},
		{"p9 p9 p9", "password", 80},
	}
	for _, c := range cases {
		p, err := compileRuleLine(c.rule)
		if err != nil {
			t.Errorf("rule %q: compile error: %v", c.rule, err)
			continue
		}
		got, ok := p.apply(c.in)
		if !ok {
			t.Errorf("rule %q on a %d-byte word: rejected, hashcat keeps the word", c.rule, len(c.in))
			continue
		}
		if len(got) != c.wantLen {
			t.Errorf("rule %q on a %d-byte word: got %d bytes, hashcat produces %d", c.rule, len(c.in), len(got), c.wantLen)
		}
	}
}

// TestHashcatRuleToggleAfterNth pins hashcat's 3NX command: toggle the case of
// the character immediately following the (N+1)th occurrence of X. With no
// such occurrence, or nothing after it, the word is unchanged.
//
// Oracle (hashcat 7.1.2) — note this TOGGLES rather than uppercases:
//
//	"30 " on "foo bar baz qux" -> "foo Bar baz qux"
//	"30 " on "foo Bar"         -> "foo bar"
//	"31 " on "a b c d e"       -> "a b C d e"
func TestHashcatRuleToggleAfterNth(t *testing.T) {
	cases := []struct{ rule, in, want string }{
		{"30 ", "foo bar baz qux", "foo Bar baz qux"},
		{"31 ", "foo bar baz qux", "foo bar Baz qux"},
		{"32 ", "foo bar baz qux", "foo bar baz Qux"},
		{"39 ", "foo bar baz qux", "foo bar baz qux"},
		{"30 ", "hELLO wORLD", "hELLO WORLD"},
		{"30 ", "foo Bar", "foo bar"},
		{"30 ", "foo 1ar", "foo 1ar"},
		{"30 ", "foo ", "foo "},
		{"30 ", "nospaces", "nospaces"},
		{"31 ", "a b c d e", "a b C d e"},
		{"30-", "a-b-c-d", "a-B-c-d"},
		{"31-", "a-b-c-d", "a-b-C-d"},
		{"30-", "foo bar", "foo bar"},
	}
	for _, c := range cases {
		p, err := compileRuleLine(c.rule)
		if err != nil {
			t.Errorf("rule %q: compile error: %v", c.rule, err)
			continue
		}
		got, ok := p.apply(c.in)
		if !ok {
			t.Errorf("rule %q on %q: rejected, hashcat produces %q", c.rule, c.in, c.want)
			continue
		}
		if got != c.want {
			t.Errorf("rule %q on %q: got %q, hashcat produces %q", c.rule, c.in, got, c.want)
		}
	}
}
