//go:build amd64

package smith

// sha1g8AVX2 and sha1g16AVX2 are the N=1 (8-lane) and N=2 (16-lane) AVX2
// SHA-1 compression cores; the assembly lives in sha1avx2_amd64.s
// (generated by sha1avx2_gen.py). Both are generated and kept, exactly like
// md5g16AVX2/md5g24AVX2 — the differential tests run against both, and
// sha1Group16AVX2 uses the N=2 core, since sha1avx2_gen.py's register-reuse
// derivation shows SHA-1 (unlike SHA-256) has room for it: 5 state + 3
// scratch = 8 YMM/chain, N=2 fits exactly in 16.
//
// ivvec is per-lane (word w, lane l holds LANE l's own starting state
// word w), not a shared broadcast IV — see sha256avx2_amd64.go's own
// comment on sha256g8AVX2 for why: HMAC continuation needs each candidate
// to resume from its own precomputed state.
// Argument order matches the generator's actual prologue exactly: out
// pointers, then msg pointers, then ivvec pointers, then kvec last — go
// vet's asmdecl check caught an earlier draft that declared kvec before
// ivvec here, which does not match sha1avx2_gen.py's prologue-building
// loop order.
func sha1g8AVX2(out0 *[5][8]uint32, msg0 *[80][8]uint32, ivvec0 *[5][8]uint32, kvec *[80][8]uint32)

func sha1g16AVX2(out0, out1 *[5][8]uint32, msg0, msg1 *[80][8]uint32, ivvec0, ivvec1 *[5][8]uint32, kvec *[80][8]uint32)

// sha1AVX2Kvec holds the 80 SHA-1 round constants (4 distinct values,
// repeated 20 times each — see sha1_scalar.go's sha1K), pre-broadcast into
// all 8 lanes, exactly like sha256AVX2Kvec.
var sha1AVX2Kvec [80][8]uint32

func init() {
	for i, v := range sha1K {
		sha1AVX2Kvec[i] = [8]uint32{v, v, v, v, v, v, v, v}
	}
}

// sha1Group16AVX2 compresses 16 lanes at once through the real N=2 AVX2
// core. states holds each lane's starting state (word-major, lane-minor:
// states[w][l]); schedules holds each lane's already-expanded 80-word
// schedule in the same layout. Internally split into the two 8-lane chains
// the assembly actually operates on (lanes 0-7 -> chain 0, 8-15 -> chain
// 1) and reassembled on the way out, so callers see one flat 16-lane
// interface — the same shape sha256Group8AVX2 presents for its 8, just
// twice as wide.
func sha1Group16AVX2(states *[5][16]uint32, schedules *[80][16]uint32) [5][16]uint32 {
	var iv0, iv1 [5][8]uint32
	var msg0, msg1 [80][8]uint32
	for w := 0; w < 5; w++ {
		for l := 0; l < 8; l++ {
			iv0[w][l] = states[w][l]
			iv1[w][l] = states[w][l+8]
		}
	}
	for step := 0; step < 80; step++ {
		for l := 0; l < 8; l++ {
			msg0[step][l] = schedules[step][l]
			msg1[step][l] = schedules[step][l+8]
		}
	}
	var out0, out1 [5][8]uint32
	sha1g16AVX2(&out0, &out1, &msg0, &msg1, &iv0, &iv1, &sha1AVX2Kvec)

	var out [5][16]uint32
	for w := 0; w < 5; w++ {
		for l := 0; l < 8; l++ {
			out[w][l] = out0[w][l]
			out[w][l+8] = out1[w][l]
		}
	}
	return out
}

// hasSHA1AVX2 reports whether this CPU supports AVX2 — a thin alias, like
// hasSHA256AVX2, kept as its own name so a caller reads "does the SHA-1
// core apply" without reaching into another file.
func hasSHA1AVX2() bool { return hasAVX2() }
