//go:build amd64

package smith

// sha256g8AVX2 is the 8-lane AVX2 SHA-256 compression core; the assembly
// lives in sha256avx2_amd64.s (generated by sha256avx2_gen.py). It compresses
// 8 independent [64-word schedule, 8-word state] pairs at once, one call
// per block per lane group.
//
// Unlike md5g24AVX2's ivvec (a single broadcast IV shared by every lane,
// since a fresh MD5 hash always starts there), ivvec here is per-lane: word
// w, lane l holds LANE l's own starting state word w. This is deliberate,
// not an oversight — the PBKDF2 lane hasher this core exists for continues
// each of its 8 candidates' HMAC computation from that CANDIDATE's own
// precomputed inner/outer state, which differs lane to lane (it depends on
// the password). Compressing from the standard IV is simply the case where
// every lane's ivvec happens to hold sha256IV.
//
//go:noescape
func sha256g8AVX2(out *[8][8]uint32, msg *[64][8]uint32, kvec *[64][8]uint32, ivvec *[8][8]uint32)

// sha256AVX2Kvec holds the 64 SHA-256 round constants, each pre-broadcast
// into all 8 AVX2 lanes, exactly like md5AVX2Kvec.
var sha256AVX2Kvec [64][8]uint32

func init() {
	for i, v := range sha256K {
		sha256AVX2Kvec[i] = [8]uint32{v, v, v, v, v, v, v, v}
	}
}

// sha256Group8AVX2 compresses 8 lanes at once through the real AVX2 core.
// states holds each lane's starting state (word-major, lane-minor:
// states[w][l]); schedules holds each lane's already-expanded 64-word
// message schedule in the same layout. Both must already be in this
// [word/step][lane] layout — sha256Group8Generic (sha256avx2_generic.go)
// takes the same shapes so callers work unmodified on any architecture.
func sha256Group8AVX2(states *[8][8]uint32, schedules *[64][8]uint32) [8][8]uint32 {
	var out [8][8]uint32
	sha256g8AVX2(&out, schedules, &sha256AVX2Kvec, states)
	return out
}

// hasSHA256AVX2 reports whether this CPU supports AVX2, so callers can
// decide whether sha256Group8AVX2 is safe to dispatch to. It is a thin
// alias over the existing hasAVX2 (md5avx2_amd64.go) — AVX2 is AVX2
// regardless of which core uses it — kept as a separate name so a caller
// reads "does the SHA-256 core apply" without reaching into MD5's file.
func hasSHA256AVX2() bool { return hasAVX2() }
