//go:build amd64

package smith

// sha512g4AVX2 is the 4-lane AVX2 SHA-512 compression core; the assembly
// lives in sha512avx2_amd64.s (generated by sha512avx2_gen.py). Same
// per-lane ivvec design as sha256g8AVX2 — see that function's own comment
// for why HMAC continuation needs it.
func sha512g4AVX2(out *[8][4]uint64, msg *[80][4]uint64, kvec *[80][4]uint64, ivvec *[8][4]uint64)

// sha512AVX2Kvec holds the 80 SHA-512 round constants, pre-broadcast into
// all 4 AVX2 lanes.
var sha512AVX2Kvec [80][4]uint64

func init() {
	for i, v := range sha512K {
		sha512AVX2Kvec[i] = [4]uint64{v, v, v, v}
	}
}

// sha512Group4AVX2 compresses 4 lanes at once through the real AVX2 core —
// sha256Group8AVX2's twin, at SHA-512's own lane width.
func sha512Group4AVX2(states *[8][4]uint64, schedules *[80][4]uint64) [8][4]uint64 {
	var out [8][4]uint64
	sha512g4AVX2(&out, schedules, &sha512AVX2Kvec, states)
	return out
}

// hasSHA512AVX2 reports whether this CPU supports AVX2 — a thin alias,
// like hasSHA256AVX2/hasSHA1AVX2.
func hasSHA512AVX2() bool { return hasAVX2() }
