"""Generator for sha512avx2_amd64.s — a 4-lane AVX2 SHA-512 compression
core, N=1 chain. A direct structural port of sha256avx2_gen.py: SHA-512 is
not a distinct algorithm design from SHA-256, just the same round function
(T1=h+Sigma1(e)+Ch(e,f,g)+K[t]+W[t], T2=Sigma0(a)+Maj(a,b,c), the same
state-shift-by-relabeling) generalized to 64-bit words — see
sha256avx2_gen.py's own docstring for the full register-budget derivation,
which applies here UNCHANGED in register COUNT (8 state + 4 scratch = 12
YMM/chain, N=1 only) since register pressure depends on how many distinct
values are live, not how wide each one is.

What actually changes, and why this needed its own generator rather than a
parameter on sha256avx2_gen.py:

  - **Lane width is 4, not 8.** One YMM register holds 4 uint64s where it
    held 8 uint32s — half the candidates in flight per call, an intrinsic
    cost of the wider word, not a register-budget choice.
  - **Instruction mnemonics gain a Q suffix**: VPSRLQ/VPSLLQ/VPADDQ do the
    same jobs as SHA-256's VPSRLD/VPSLLD/VPADDD, operating on 4x64-bit
    lanes instead of 8x32-bit ones. VPXOR/VPAND/VPOR need no suffix change
    — they are bitwise, lane-width-agnostic on any x86 vector ISA.
  - **Rotation amounts and round count differ** (Sigma1=14/18/41,
    Sigma0=28/34/39, 80 rounds instead of 64) — FIPS 180-4's own SHA-512
    constants, substituted into the identical control structure.
  - **The message schedule stays in Go** (sha512_scalar.go's
    sha512ExpandSchedule), same design decision as SHA-256's, for the same
    reason: SHA-512's schedule expansion is no more complex to write in Go
    than SHA-256's, and keeping it there keeps this generator's hot loop
    structurally identical to the proven one.

Regenerate with: `python3 sha512avx2_gen.py` from this directory. Do not
hand-edit sha512avx2_amd64.s — edit this file and regenerate instead.
"""

import os

LANES = 4  # AVX2: one YMM = 4x uint64

SIGMA1_ROTS = (14, 18, 41)
SIGMA0_ROTS = (28, 34, 39)


def sigma(dst, x, rots, t2, t3):
    """Emit dst := ROTR(x,rots[0]) ^ ROTR(x,rots[1]) ^ ROTR(x,rots[2]) using
    the 64-bit (Q) shift/or/xor forms — identical shape to sha256avx2_gen's
    sigma, substituting VPSRLQ/VPSLLQ for VPSRLD/VPSLLD."""
    lines = []
    n0, n1, n2 = rots
    lines.append('\tVPSRLQ $%d, %s, %s' % (n0, x, dst))
    lines.append('\tVPSLLQ $%d, %s, %s' % (64 - n0, x, t2))
    lines.append('\tVPOR %s, %s, %s' % (t2, dst, dst))
    for n in (n1, n2):
        lines.append('\tVPSRLQ $%d, %s, %s' % (n, x, t2))
        lines.append('\tVPSLLQ $%d, %s, %s' % (64 - n, x, t3))
        lines.append('\tVPOR %s, %s, %s' % (t3, t2, t2))
        lines.append('\tVPXOR %s, %s, %s' % (t2, dst, dst))
    return lines


def round_block(step, regs, T, msg_reg, kvec_reg):
    a, b, c, d, e, f, g, h = regs
    T0, T1, T2, T3 = T
    woff = step * LANES * 8
    koff = step * LANES * 8
    lines = ['\t// round %d  a=%s b=%s c=%s d=%s e=%s f=%s g=%s h=%s' %
             (step, a, b, c, d, e, f, g, h)]

    lines += sigma(T0, e, SIGMA1_ROTS, T2, T3)
    lines.append('\tVPXOR %s, %s, %s' % (g, f, T2))
    lines.append('\tVPAND %s, %s, %s' % (e, T2, T2))
    lines.append('\tVPXOR %s, %s, %s' % (g, T2, T2))
    lines.append('\tVPADDQ %s, %s, %s' % (T2, T0, T0))
    lines.append('\tVPADDQ %s, %s, %s' % (h, T0, T0))
    lines.append('\tVPADDQ %d(%s), %s, %s' % (koff, kvec_reg, T0, T0))
    lines.append('\tVPADDQ %d(%s), %s, %s' % (woff, msg_reg, T0, T0))

    lines += sigma(T1, a, SIGMA0_ROTS, T2, T3)
    lines.append('\tVPXOR %s, %s, %s' % (b, a, T2))
    lines.append('\tVPAND %s, %s, %s' % (b, a, T3))
    lines.append('\tVPAND %s, %s, %s' % (T2, c, T2))
    lines.append('\tVPXOR %s, %s, %s' % (T3, T2, T2))
    lines.append('\tVPADDQ %s, %s, %s' % (T2, T1, T1))

    lines.append('\tVPADDQ %s, %s, %s' % (T0, d, d))
    lines.append('\tVPADDQ %s, %s, %s' % (T1, T0, h))
    lines.append('')

    new_regs = [h, a, b, c, d, e, f, g]
    return lines, new_regs


HEADER = '''// Code generated by sha512avx2_gen.py. DO NOT EDIT BY HAND — edit
// sha512avx2_gen.py and regenerate with `python3 sha512avx2_gen.py` from
// this directory.
//
// AVX2 4-lane SHA-512 compression core, one chain (%(group)d candidates in
// flight per call) — a direct structural port of sha256avx2_gen.py's
// SHA-256 core (see that generator's docstring for the shared
// register-budget derivation: 8 state + 4 scratch = 12 YMM, N=1 is the
// only chain count that fits), widened to 64-bit words: VPSRLQ/VPSLLQ/
// VPADDQ in place of the D-suffixed forms, 4 lanes/register instead of 8,
// SHA-512's own rotation amounts and 80 rounds instead of 64.
//
// Message layout: word-major, lane-minor [80][4]uint64 — the fully
// expanded 80-word schedule (see sha512_scalar.go's sha512ExpandSchedule),
// word t at byte offset t*32 (4 lanes * 8 bytes/uint64 = 32, same stride in
// bytes as SHA-256's [64][8]uint32 despite the different shape — one YMM
// register's worth either way). K layout: [80][4]uint64, step t at byte
// offset t*32, each K value pre-broadcast to all 4 lanes. State in/out
// layout: [8][4]uint64, word w (a..h, index 0..7) at byte offset w*32.
#include "textflag.h"

// func %(funcname)s(out *[8][4]uint64, msg *[80][4]uint64, kvec *[80][4]uint64, ivvec *[8][4]uint64)
TEXT ·%(funcname)s(SB), NOSPLIT, $0-32
	MOVQ out+0(FP), AX
	MOVQ msg+8(FP), BX
	MOVQ kvec+16(FP), CX
	MOVQ ivvec+24(FP), DX

%(load_state)s
'''

STATE_REGS = ['Y0', 'Y1', 'Y2', 'Y3', 'Y4', 'Y5', 'Y6', 'Y7']
SCRATCH_REGS = ['Y8', 'Y9', 'Y10', 'Y11']


def generate(funcname, outpath):
    regs = list(STATE_REGS)
    T = list(SCRATCH_REGS)

    load_state = []
    for w in range(8):
        load_state.append('\tVMOVDQU %d(DX), %s' % (w * LANES * 8, regs[w]))

    lines = []
    for step in range(80):
        blk, regs = round_block(step, regs, T, 'BX', 'CX')
        lines += blk
    body = '\n'.join(lines)

    footer_lines = []
    for w in range(8):
        footer_lines.append('\tVPADDQ %d(DX), %s, %s' % (w * LANES * 8, regs[w], regs[w]))
    for w in range(8):
        footer_lines.append('\tVMOVDQU %s, %d(AX)' % (regs[w], w * LANES * 8))
    footer_lines.append('\tVZEROUPPER')
    footer_lines.append('\tRET')

    header = HEADER % {'funcname': funcname, 'group': LANES, 'load_state': '\n'.join(load_state)}

    with open(outpath, 'w') as f:
        f.write(header)
        f.write('\n')
        f.write(body)
        f.write('\n'.join(footer_lines))
        f.write('\n')
    print('generated', outpath, 'group=', LANES, 'yregs= 12 (8 state + 4 scratch)')


if __name__ == '__main__':
    outdir = os.path.dirname(os.path.abspath(__file__))
    outpath = os.path.join(outdir, 'sha512avx2_amd64.s')
    generate('sha512g4AVX2', outpath)
