//go:build amd64

package smith

// sha512ScheduleExpand4AVX2 expands a SHA-512 message schedule's words
// 16..79 from its already-populated words 0..15, for all 4 AVX2 lanes at
// once; the assembly lives in sha512scheduleavx2_amd64.s (generated by
// sha512schedule_avx2_gen.py). w is modified in place.
func sha512ScheduleExpand4AVX2(w *[80][4]uint64)
