"""Generator for sha512scheduleavx2_amd64.s — vectorizes PBKDF2-HMAC-
SHA512's message-schedule expansion (FIPS 180-4 Sec 6.4.2 step 1) across
all 4 AVX2 lanes at once, in place, given the schedule's first 16 words
already populated (sha512ScheduleFirst16FromWords's job, in Go).

Why this exists: the diagnostic benchmark that separated schedule
expansion from compression (pbkdf2_avx2_bench_test.go, from the earlier
word-native-fix investigation) found schedule expansion the larger
remaining cost for SHA-512 after that fix — this is the next lever, not a
new idea; the design doc's original "message schedule stays in Go" call
was made before that diagnostic existed to say which of the two mattered
more for which hash.

SHA-512's recurrence, for i = 16..79:

    s0 = ROTR(w[i-15],1) ^ ROTR(w[i-15],8) ^ (w[i-15]>>7)
    s1 = ROTR(w[i-2],19) ^ ROTR(w[i-2],61) ^ (w[i-2]>>6)
    w[i] = w[i-16] + s0 + w[i-7] + s1

is a pure memory-to-memory recurrence with NO cross-lane dependency — each
of the 4 lanes' schedules expand independently, the same multi-buffer
shape as the compression core (sha512avx2_gen.py) — but simpler: every
read index (i-16, i-15, i-7, i-2) is strictly less than the write index i,
so unrolling the 64 steps in program order needs no register-budget
derivation the way the compression core did. No state is carried between
steps beyond what each step re-reads from w itself; a handful of scratch
YMM registers, reused every step, is enough.

Message layout: identical to sha512avx2_gen.py's msg parameter —
word-major, lane-minor [80][4]uint64, word t at byte offset t*32.

Regenerate with: `python3 sha512schedule_avx2_gen.py` from this directory.
Do not hand-edit sha512scheduleavx2_amd64.s — edit this file and
regenerate instead.
"""

import os

LANES = 4
STRIDE = LANES * 8  # bytes per schedule word (32)


def small_sigma(dst, x, rot1, rot2, shift, t2, t3):
    """Emit dst := ROTR(x,rot1) ^ ROTR(x,rot2) ^ (x >> shift) — the
    schedule's small-sigma shape (two rotates and a plain shift), distinct
    from the compression core's Sigma (three rotates) in sha512avx2_gen.py."""
    lines = []
    lines.append('\tVPSRLQ $%d, %s, %s' % (rot1, x, dst))
    lines.append('\tVPSLLQ $%d, %s, %s' % (64 - rot1, x, t2))
    lines.append('\tVPOR %s, %s, %s' % (t2, dst, dst))
    lines.append('\tVPSRLQ $%d, %s, %s' % (rot2, x, t2))
    lines.append('\tVPSLLQ $%d, %s, %s' % (64 - rot2, x, t3))
    lines.append('\tVPOR %s, %s, %s' % (t3, t2, t2))
    lines.append('\tVPXOR %s, %s, %s' % (t2, dst, dst))
    lines.append('\tVPSRLQ $%d, %s, %s' % (shift, x, t2))
    lines.append('\tVPXOR %s, %s, %s' % (t2, dst, dst))
    return lines


def step_block(i, msg_reg):
    """Emit w[i] = w[i-16] + sigma0(w[i-15]) + w[i-7] + sigma1(w[i-2])."""
    off15 = (i - 15) * STRIDE
    off16 = (i - 16) * STRIDE
    off7 = (i - 7) * STRIDE
    off2 = (i - 2) * STRIDE
    offi = i * STRIDE

    lines = ['\t// w[%d]' % i]
    lines.append('\tVMOVDQU %d(%s), Y0' % (off15, msg_reg))
    lines += small_sigma('Y1', 'Y0', 1, 8, 7, 'Y2', 'Y3')  # Y1 = sigma0(w[i-15])

    lines.append('\tVMOVDQU %d(%s), Y0' % (off2, msg_reg))
    lines += small_sigma('Y4', 'Y0', 19, 61, 6, 'Y2', 'Y3')  # Y4 = sigma1(w[i-2])

    lines.append('\tVMOVDQU %d(%s), Y0' % (off16, msg_reg))
    lines.append('\tVPADDQ Y1, Y0, Y0')
    lines.append('\tVMOVDQU %d(%s), Y2' % (off7, msg_reg))
    lines.append('\tVPADDQ Y2, Y0, Y0')
    lines.append('\tVPADDQ Y4, Y0, Y0')
    lines.append('\tVMOVDQU Y0, %d(%s)' % (offi, msg_reg))
    lines.append('')
    return lines


HEADER = '''// Code generated by sha512schedule_avx2_gen.py. DO NOT EDIT BY HAND —
// edit sha512schedule_avx2_gen.py and regenerate with
// `python3 sha512schedule_avx2_gen.py` from this directory.
//
// AVX2 4-lane SHA-512 message-schedule expansion, in place: given w[0..15]
// already populated (sha512ScheduleFirst16FromWords's job, in Go),
// computes w[16..79] per FIPS 180-4 Sec 6.4.2 step 1, all 4 lanes at once
// per word. See sha512schedule_avx2_gen.py's own docstring for why this
// needed no register-budget derivation the compression core's generator
// did: a pure memory-to-memory recurrence, no state carried between steps
// beyond what each step re-reads from w, and every read index is strictly
// less than the write index, so straight-line program order alone
// satisfies every dependency.
//
// Message layout: identical to sha512avx2_amd64.s's msg parameter —
// word-major, lane-minor [80][4]uint64, word t at byte offset t*32.
#include "textflag.h"

// func sha512ScheduleExpand4AVX2(w *[80][4]uint64)
TEXT ·sha512ScheduleExpand4AVX2(SB), NOSPLIT, $0-8
\tMOVQ w+0(FP), BX

%(body)s
\tVZEROUPPER
\tRET
'''


def generate(outpath):
    lines = []
    for i in range(16, 80):
        lines += step_block(i, 'BX')
    body = '\n'.join(lines)

    with open(outpath, 'w') as f:
        f.write(HEADER % {'body': body})
    print('generated', outpath)


if __name__ == '__main__':
    outdir = os.path.dirname(os.path.abspath(__file__))
    outpath = os.path.join(outdir, 'sha512scheduleavx2_amd64.s')
    generate(outpath)
