#!/usr/bin/env python3
"""Generate eks_lanes.go: Blowfish key schedules that advance N independent
candidates through each Feistel round together.

Why generated rather than hand-written: Go does not unroll loops, so the lanes
have to appear literally in the source for their dependency chains to interleave
in the scheduler. Four widths x sixteen rounds is far too much to maintain by
hand, and a transcription slip in round 11 of the 8-lane variant would be nearly
invisible in review.

Run: python3 bcryptlane_gen.py > eks_lanes.go && gofmt -w eks_lanes.go
"""

WIDTHS = [2, 4, 8]

def feistel(dst, src, lane, pidx):
    c = f"c{lane}"
    return (f"\tx{dst}{lane} ^= (({c}.s0[byte(x{src}{lane}>>24)] + {c}.s1[byte(x{src}{lane}>>16)]) ^ "
            f"{c}.s2[byte(x{src}{lane}>>8)]) + {c}.s3[byte(x{src}{lane})] ^ {c}.p[{pidx}]")

def emit_block(n):
    """One fully unrolled 16-round encryptBlock across n lanes."""
    args = ", ".join(f"l{i}, r{i} uint32" for i in range(n))
    cs = ", ".join(f"c{i} *state" for i in range(n))
    rets = ", ".join("uint32" for _ in range(2 * n))
    print(f"func encryptBlock{n}({args}, {cs}) ({rets}) {{")
    for i in range(n):
        print(f"\txl{i}, xr{i} := l{i}, r{i}")
    for i in range(n):
        print(f"\txl{i} ^= c{i}.p[0]")
    # rounds 1..16, alternating which half is updated
    for rnd in range(1, 17):
        dst, src = ("r", "l") if rnd % 2 == 1 else ("l", "r")
        for i in range(n):
            print(feistel(dst, src, i, rnd))
    for i in range(n):
        print(f"\txr{i} ^= c{i}.p[17]")
    print("\treturn " + ", ".join(f"xr{i}, xl{i}" for i in range(n)))
    print("}")
    print()

def emit_expand(n, salted):
    name = f"expandKeyWithSalt{n}" if salted else f"expandKey{n}"
    saltarg = ", salt []byte" if salted else ""
    print(f"func {name}(keys [{n}][]byte{saltarg}, c [{n}]*state) {{")
    print("\tfor i := 0; i < 18; i++ {")
    for i in range(n):
        print(f"\t\tc[{i}].p[i] ^= nextWord(keys[{i}], i*4)")
    print("\t}")
    for i in range(n):
        print(f"\tc{i} := c[{i}]")
    for i in range(n):
        print(f"\tvar l{i}, r{i} uint32")
    if salted:
        print("\tsj := 0")
    lanes = ", ".join(f"l{i}, r{i}" for i in range(n))
    cargs = ", ".join(f"c{i}" for i in range(n))
    def body(target, count):
        print(f"\tfor i := 0; i < {count}; i += 2 {{")
        if salted:
            for i in range(n):
                print(f"\t\tl{i} ^= saltWord(salt, sj)")
                print(f"\t\tr{i} ^= saltWord(salt, sj+4)")
            print("\t\tsj = (sj + 8) % len(salt)")
        print(f"\t\t{lanes} = encryptBlock{n}({lanes}, {cargs})")
        for i in range(n):
            print(f"\t\tc{i}.{target}[i], c{i}.{target}[i+1] = l{i}, r{i}")
        print("\t}")
    body("p", 18)
    for s in ("s0", "s1", "s2", "s3"):
        body(s, 256)
    print("}")
    print()

def emit_run(n):
    print(f"// run{n} hashes exactly {n} candidates through interleaved lanes,")
    print(f"// writing verdicts to h.verdicts[:{n}].")
    print(f"func (h *Hasher) run{n}(pw [][]byte) {{")
    print(f"	var keys [{n}][]byte")
    print(f"	var c [{n}]*state")
    print(f"	for i := 0; i < {n}; i++ {{")
    print("		// bug compatibility: the key's trailing NUL participates")
    print("		k := append(h.keyScratch[i][:0], pw[i]...)")
    print("		k = append(k, 0)")
    print("		h.keyScratch[i] = k")
    print("		keys[i] = k")
    print("		// no zeroing: initState overwrites p and s0..s3 in full;")
    print("		// clearing 4 KB per lane per batch would be pure waste.")
    print("		c[i] = &h.scratch[i]")
    print("		initState(c[i])")
    print("	}")
    print(f"	salt := h.csalt[:]")
    print(f"	expandKeyWithSalt{n}(keys, salt, c)")
    print(f"	var saltKeys [{n}][]byte")
    print(f"	for i := 0; i < {n}; i++ {{ saltKeys[i] = salt }}")
    print("	for r, rounds := uint64(0), uint64(1)<<uint(h.cost); r < rounds; r++ {")
    print(f"		expandKey{n}(keys, c)")
    print(f"		expandKey{n}(saltKeys, c)")
    print("	}")
    print(f"	for i := 0; i < {n}; i++ {{")
    print("		h.verdicts[i] = h.finish(c[i])")
    print("	}")
    print("}")
    print()

print("// Code generated by bcryptlane_gen.py. DO NOT EDIT.")
print()
print("package bcryptlane")
print()
for n in WIDTHS:
    emit_block(n)
    emit_expand(n, salted=False)
    emit_expand(n, salted=True)
    emit_run(n)
