// Code generated by bcryptlane_gen.py. DO NOT EDIT.

package bcryptlane

func encryptBlock2(l0, r0 uint32, l1, r1 uint32, c0 *state, c1 *state) (uint32, uint32, uint32, uint32) {
	xl0, xr0 := l0, r0
	xl1, xr1 := l1, r1
	xl0 ^= c0.p[0]
	xl1 ^= c1.p[0]
	xr0 ^= ((c0.s0[byte(xl0>>24)] + c0.s1[byte(xl0>>16)]) ^ c0.s2[byte(xl0>>8)]) + c0.s3[byte(xl0)] ^ c0.p[1]
	xr1 ^= ((c1.s0[byte(xl1>>24)] + c1.s1[byte(xl1>>16)]) ^ c1.s2[byte(xl1>>8)]) + c1.s3[byte(xl1)] ^ c1.p[1]
	xl0 ^= ((c0.s0[byte(xr0>>24)] + c0.s1[byte(xr0>>16)]) ^ c0.s2[byte(xr0>>8)]) + c0.s3[byte(xr0)] ^ c0.p[2]
	xl1 ^= ((c1.s0[byte(xr1>>24)] + c1.s1[byte(xr1>>16)]) ^ c1.s2[byte(xr1>>8)]) + c1.s3[byte(xr1)] ^ c1.p[2]
	xr0 ^= ((c0.s0[byte(xl0>>24)] + c0.s1[byte(xl0>>16)]) ^ c0.s2[byte(xl0>>8)]) + c0.s3[byte(xl0)] ^ c0.p[3]
	xr1 ^= ((c1.s0[byte(xl1>>24)] + c1.s1[byte(xl1>>16)]) ^ c1.s2[byte(xl1>>8)]) + c1.s3[byte(xl1)] ^ c1.p[3]
	xl0 ^= ((c0.s0[byte(xr0>>24)] + c0.s1[byte(xr0>>16)]) ^ c0.s2[byte(xr0>>8)]) + c0.s3[byte(xr0)] ^ c0.p[4]
	xl1 ^= ((c1.s0[byte(xr1>>24)] + c1.s1[byte(xr1>>16)]) ^ c1.s2[byte(xr1>>8)]) + c1.s3[byte(xr1)] ^ c1.p[4]
	xr0 ^= ((c0.s0[byte(xl0>>24)] + c0.s1[byte(xl0>>16)]) ^ c0.s2[byte(xl0>>8)]) + c0.s3[byte(xl0)] ^ c0.p[5]
	xr1 ^= ((c1.s0[byte(xl1>>24)] + c1.s1[byte(xl1>>16)]) ^ c1.s2[byte(xl1>>8)]) + c1.s3[byte(xl1)] ^ c1.p[5]
	xl0 ^= ((c0.s0[byte(xr0>>24)] + c0.s1[byte(xr0>>16)]) ^ c0.s2[byte(xr0>>8)]) + c0.s3[byte(xr0)] ^ c0.p[6]
	xl1 ^= ((c1.s0[byte(xr1>>24)] + c1.s1[byte(xr1>>16)]) ^ c1.s2[byte(xr1>>8)]) + c1.s3[byte(xr1)] ^ c1.p[6]
	xr0 ^= ((c0.s0[byte(xl0>>24)] + c0.s1[byte(xl0>>16)]) ^ c0.s2[byte(xl0>>8)]) + c0.s3[byte(xl0)] ^ c0.p[7]
	xr1 ^= ((c1.s0[byte(xl1>>24)] + c1.s1[byte(xl1>>16)]) ^ c1.s2[byte(xl1>>8)]) + c1.s3[byte(xl1)] ^ c1.p[7]
	xl0 ^= ((c0.s0[byte(xr0>>24)] + c0.s1[byte(xr0>>16)]) ^ c0.s2[byte(xr0>>8)]) + c0.s3[byte(xr0)] ^ c0.p[8]
	xl1 ^= ((c1.s0[byte(xr1>>24)] + c1.s1[byte(xr1>>16)]) ^ c1.s2[byte(xr1>>8)]) + c1.s3[byte(xr1)] ^ c1.p[8]
	xr0 ^= ((c0.s0[byte(xl0>>24)] + c0.s1[byte(xl0>>16)]) ^ c0.s2[byte(xl0>>8)]) + c0.s3[byte(xl0)] ^ c0.p[9]
	xr1 ^= ((c1.s0[byte(xl1>>24)] + c1.s1[byte(xl1>>16)]) ^ c1.s2[byte(xl1>>8)]) + c1.s3[byte(xl1)] ^ c1.p[9]
	xl0 ^= ((c0.s0[byte(xr0>>24)] + c0.s1[byte(xr0>>16)]) ^ c0.s2[byte(xr0>>8)]) + c0.s3[byte(xr0)] ^ c0.p[10]
	xl1 ^= ((c1.s0[byte(xr1>>24)] + c1.s1[byte(xr1>>16)]) ^ c1.s2[byte(xr1>>8)]) + c1.s3[byte(xr1)] ^ c1.p[10]
	xr0 ^= ((c0.s0[byte(xl0>>24)] + c0.s1[byte(xl0>>16)]) ^ c0.s2[byte(xl0>>8)]) + c0.s3[byte(xl0)] ^ c0.p[11]
	xr1 ^= ((c1.s0[byte(xl1>>24)] + c1.s1[byte(xl1>>16)]) ^ c1.s2[byte(xl1>>8)]) + c1.s3[byte(xl1)] ^ c1.p[11]
	xl0 ^= ((c0.s0[byte(xr0>>24)] + c0.s1[byte(xr0>>16)]) ^ c0.s2[byte(xr0>>8)]) + c0.s3[byte(xr0)] ^ c0.p[12]
	xl1 ^= ((c1.s0[byte(xr1>>24)] + c1.s1[byte(xr1>>16)]) ^ c1.s2[byte(xr1>>8)]) + c1.s3[byte(xr1)] ^ c1.p[12]
	xr0 ^= ((c0.s0[byte(xl0>>24)] + c0.s1[byte(xl0>>16)]) ^ c0.s2[byte(xl0>>8)]) + c0.s3[byte(xl0)] ^ c0.p[13]
	xr1 ^= ((c1.s0[byte(xl1>>24)] + c1.s1[byte(xl1>>16)]) ^ c1.s2[byte(xl1>>8)]) + c1.s3[byte(xl1)] ^ c1.p[13]
	xl0 ^= ((c0.s0[byte(xr0>>24)] + c0.s1[byte(xr0>>16)]) ^ c0.s2[byte(xr0>>8)]) + c0.s3[byte(xr0)] ^ c0.p[14]
	xl1 ^= ((c1.s0[byte(xr1>>24)] + c1.s1[byte(xr1>>16)]) ^ c1.s2[byte(xr1>>8)]) + c1.s3[byte(xr1)] ^ c1.p[14]
	xr0 ^= ((c0.s0[byte(xl0>>24)] + c0.s1[byte(xl0>>16)]) ^ c0.s2[byte(xl0>>8)]) + c0.s3[byte(xl0)] ^ c0.p[15]
	xr1 ^= ((c1.s0[byte(xl1>>24)] + c1.s1[byte(xl1>>16)]) ^ c1.s2[byte(xl1>>8)]) + c1.s3[byte(xl1)] ^ c1.p[15]
	xl0 ^= ((c0.s0[byte(xr0>>24)] + c0.s1[byte(xr0>>16)]) ^ c0.s2[byte(xr0>>8)]) + c0.s3[byte(xr0)] ^ c0.p[16]
	xl1 ^= ((c1.s0[byte(xr1>>24)] + c1.s1[byte(xr1>>16)]) ^ c1.s2[byte(xr1>>8)]) + c1.s3[byte(xr1)] ^ c1.p[16]
	xr0 ^= c0.p[17]
	xr1 ^= c1.p[17]
	return xr0, xl0, xr1, xl1
}

func expandKey2(keys [2][]byte, c [2]*state) {
	for i := 0; i < 18; i++ {
		c[0].p[i] ^= nextWord(keys[0], i*4)
		c[1].p[i] ^= nextWord(keys[1], i*4)
	}
	c0 := c[0]
	c1 := c[1]
	var l0, r0 uint32
	var l1, r1 uint32
	for i := 0; i < 18; i += 2 {
		l0, r0, l1, r1 = encryptBlock2(l0, r0, l1, r1, c0, c1)
		c0.p[i], c0.p[i+1] = l0, r0
		c1.p[i], c1.p[i+1] = l1, r1
	}
	for i := 0; i < 256; i += 2 {
		l0, r0, l1, r1 = encryptBlock2(l0, r0, l1, r1, c0, c1)
		c0.s0[i], c0.s0[i+1] = l0, r0
		c1.s0[i], c1.s0[i+1] = l1, r1
	}
	for i := 0; i < 256; i += 2 {
		l0, r0, l1, r1 = encryptBlock2(l0, r0, l1, r1, c0, c1)
		c0.s1[i], c0.s1[i+1] = l0, r0
		c1.s1[i], c1.s1[i+1] = l1, r1
	}
	for i := 0; i < 256; i += 2 {
		l0, r0, l1, r1 = encryptBlock2(l0, r0, l1, r1, c0, c1)
		c0.s2[i], c0.s2[i+1] = l0, r0
		c1.s2[i], c1.s2[i+1] = l1, r1
	}
	for i := 0; i < 256; i += 2 {
		l0, r0, l1, r1 = encryptBlock2(l0, r0, l1, r1, c0, c1)
		c0.s3[i], c0.s3[i+1] = l0, r0
		c1.s3[i], c1.s3[i+1] = l1, r1
	}
}

func expandKeyWithSalt2(keys [2][]byte, salt []byte, c [2]*state) {
	for i := 0; i < 18; i++ {
		c[0].p[i] ^= nextWord(keys[0], i*4)
		c[1].p[i] ^= nextWord(keys[1], i*4)
	}
	c0 := c[0]
	c1 := c[1]
	var l0, r0 uint32
	var l1, r1 uint32
	sj := 0
	for i := 0; i < 18; i += 2 {
		l0 ^= saltWord(salt, sj)
		r0 ^= saltWord(salt, sj+4)
		l1 ^= saltWord(salt, sj)
		r1 ^= saltWord(salt, sj+4)
		sj = (sj + 8) % len(salt)
		l0, r0, l1, r1 = encryptBlock2(l0, r0, l1, r1, c0, c1)
		c0.p[i], c0.p[i+1] = l0, r0
		c1.p[i], c1.p[i+1] = l1, r1
	}
	for i := 0; i < 256; i += 2 {
		l0 ^= saltWord(salt, sj)
		r0 ^= saltWord(salt, sj+4)
		l1 ^= saltWord(salt, sj)
		r1 ^= saltWord(salt, sj+4)
		sj = (sj + 8) % len(salt)
		l0, r0, l1, r1 = encryptBlock2(l0, r0, l1, r1, c0, c1)
		c0.s0[i], c0.s0[i+1] = l0, r0
		c1.s0[i], c1.s0[i+1] = l1, r1
	}
	for i := 0; i < 256; i += 2 {
		l0 ^= saltWord(salt, sj)
		r0 ^= saltWord(salt, sj+4)
		l1 ^= saltWord(salt, sj)
		r1 ^= saltWord(salt, sj+4)
		sj = (sj + 8) % len(salt)
		l0, r0, l1, r1 = encryptBlock2(l0, r0, l1, r1, c0, c1)
		c0.s1[i], c0.s1[i+1] = l0, r0
		c1.s1[i], c1.s1[i+1] = l1, r1
	}
	for i := 0; i < 256; i += 2 {
		l0 ^= saltWord(salt, sj)
		r0 ^= saltWord(salt, sj+4)
		l1 ^= saltWord(salt, sj)
		r1 ^= saltWord(salt, sj+4)
		sj = (sj + 8) % len(salt)
		l0, r0, l1, r1 = encryptBlock2(l0, r0, l1, r1, c0, c1)
		c0.s2[i], c0.s2[i+1] = l0, r0
		c1.s2[i], c1.s2[i+1] = l1, r1
	}
	for i := 0; i < 256; i += 2 {
		l0 ^= saltWord(salt, sj)
		r0 ^= saltWord(salt, sj+4)
		l1 ^= saltWord(salt, sj)
		r1 ^= saltWord(salt, sj+4)
		sj = (sj + 8) % len(salt)
		l0, r0, l1, r1 = encryptBlock2(l0, r0, l1, r1, c0, c1)
		c0.s3[i], c0.s3[i+1] = l0, r0
		c1.s3[i], c1.s3[i+1] = l1, r1
	}
}

// run2 hashes exactly 2 candidates through interleaved lanes,
// writing verdicts to h.verdicts[:2].
func (h *Hasher) run2(pw [][]byte) {
	var keys [2][]byte
	var c [2]*state
	for i := 0; i < 2; i++ {
		// bug compatibility: the key's trailing NUL participates
		k := append(h.keyScratch[i][:0], pw[i]...)
		k = append(k, 0)
		h.keyScratch[i] = k
		keys[i] = k
		// no zeroing: initState overwrites p and s0..s3 in full;
		// clearing 4 KB per lane per batch would be pure waste.
		c[i] = &h.scratch[i]
		initState(c[i])
	}
	salt := h.csalt[:]
	expandKeyWithSalt2(keys, salt, c)
	var saltKeys [2][]byte
	for i := 0; i < 2; i++ {
		saltKeys[i] = salt
	}
	for r, rounds := uint64(0), uint64(1)<<uint(h.cost); r < rounds; r++ {
		expandKey2(keys, c)
		expandKey2(saltKeys, c)
	}
	for i := 0; i < 2; i++ {
		h.verdicts[i] = h.finish(c[i])
	}
}

func encryptBlock4(l0, r0 uint32, l1, r1 uint32, l2, r2 uint32, l3, r3 uint32, c0 *state, c1 *state, c2 *state, c3 *state) (uint32, uint32, uint32, uint32, uint32, uint32, uint32, uint32) {
	xl0, xr0 := l0, r0
	xl1, xr1 := l1, r1
	xl2, xr2 := l2, r2
	xl3, xr3 := l3, r3
	xl0 ^= c0.p[0]
	xl1 ^= c1.p[0]
	xl2 ^= c2.p[0]
	xl3 ^= c3.p[0]
	xr0 ^= ((c0.s0[byte(xl0>>24)] + c0.s1[byte(xl0>>16)]) ^ c0.s2[byte(xl0>>8)]) + c0.s3[byte(xl0)] ^ c0.p[1]
	xr1 ^= ((c1.s0[byte(xl1>>24)] + c1.s1[byte(xl1>>16)]) ^ c1.s2[byte(xl1>>8)]) + c1.s3[byte(xl1)] ^ c1.p[1]
	xr2 ^= ((c2.s0[byte(xl2>>24)] + c2.s1[byte(xl2>>16)]) ^ c2.s2[byte(xl2>>8)]) + c2.s3[byte(xl2)] ^ c2.p[1]
	xr3 ^= ((c3.s0[byte(xl3>>24)] + c3.s1[byte(xl3>>16)]) ^ c3.s2[byte(xl3>>8)]) + c3.s3[byte(xl3)] ^ c3.p[1]
	xl0 ^= ((c0.s0[byte(xr0>>24)] + c0.s1[byte(xr0>>16)]) ^ c0.s2[byte(xr0>>8)]) + c0.s3[byte(xr0)] ^ c0.p[2]
	xl1 ^= ((c1.s0[byte(xr1>>24)] + c1.s1[byte(xr1>>16)]) ^ c1.s2[byte(xr1>>8)]) + c1.s3[byte(xr1)] ^ c1.p[2]
	xl2 ^= ((c2.s0[byte(xr2>>24)] + c2.s1[byte(xr2>>16)]) ^ c2.s2[byte(xr2>>8)]) + c2.s3[byte(xr2)] ^ c2.p[2]
	xl3 ^= ((c3.s0[byte(xr3>>24)] + c3.s1[byte(xr3>>16)]) ^ c3.s2[byte(xr3>>8)]) + c3.s3[byte(xr3)] ^ c3.p[2]
	xr0 ^= ((c0.s0[byte(xl0>>24)] + c0.s1[byte(xl0>>16)]) ^ c0.s2[byte(xl0>>8)]) + c0.s3[byte(xl0)] ^ c0.p[3]
	xr1 ^= ((c1.s0[byte(xl1>>24)] + c1.s1[byte(xl1>>16)]) ^ c1.s2[byte(xl1>>8)]) + c1.s3[byte(xl1)] ^ c1.p[3]
	xr2 ^= ((c2.s0[byte(xl2>>24)] + c2.s1[byte(xl2>>16)]) ^ c2.s2[byte(xl2>>8)]) + c2.s3[byte(xl2)] ^ c2.p[3]
	xr3 ^= ((c3.s0[byte(xl3>>24)] + c3.s1[byte(xl3>>16)]) ^ c3.s2[byte(xl3>>8)]) + c3.s3[byte(xl3)] ^ c3.p[3]
	xl0 ^= ((c0.s0[byte(xr0>>24)] + c0.s1[byte(xr0>>16)]) ^ c0.s2[byte(xr0>>8)]) + c0.s3[byte(xr0)] ^ c0.p[4]
	xl1 ^= ((c1.s0[byte(xr1>>24)] + c1.s1[byte(xr1>>16)]) ^ c1.s2[byte(xr1>>8)]) + c1.s3[byte(xr1)] ^ c1.p[4]
	xl2 ^= ((c2.s0[byte(xr2>>24)] + c2.s1[byte(xr2>>16)]) ^ c2.s2[byte(xr2>>8)]) + c2.s3[byte(xr2)] ^ c2.p[4]
	xl3 ^= ((c3.s0[byte(xr3>>24)] + c3.s1[byte(xr3>>16)]) ^ c3.s2[byte(xr3>>8)]) + c3.s3[byte(xr3)] ^ c3.p[4]
	xr0 ^= ((c0.s0[byte(xl0>>24)] + c0.s1[byte(xl0>>16)]) ^ c0.s2[byte(xl0>>8)]) + c0.s3[byte(xl0)] ^ c0.p[5]
	xr1 ^= ((c1.s0[byte(xl1>>24)] + c1.s1[byte(xl1>>16)]) ^ c1.s2[byte(xl1>>8)]) + c1.s3[byte(xl1)] ^ c1.p[5]
	xr2 ^= ((c2.s0[byte(xl2>>24)] + c2.s1[byte(xl2>>16)]) ^ c2.s2[byte(xl2>>8)]) + c2.s3[byte(xl2)] ^ c2.p[5]
	xr3 ^= ((c3.s0[byte(xl3>>24)] + c3.s1[byte(xl3>>16)]) ^ c3.s2[byte(xl3>>8)]) + c3.s3[byte(xl3)] ^ c3.p[5]
	xl0 ^= ((c0.s0[byte(xr0>>24)] + c0.s1[byte(xr0>>16)]) ^ c0.s2[byte(xr0>>8)]) + c0.s3[byte(xr0)] ^ c0.p[6]
	xl1 ^= ((c1.s0[byte(xr1>>24)] + c1.s1[byte(xr1>>16)]) ^ c1.s2[byte(xr1>>8)]) + c1.s3[byte(xr1)] ^ c1.p[6]
	xl2 ^= ((c2.s0[byte(xr2>>24)] + c2.s1[byte(xr2>>16)]) ^ c2.s2[byte(xr2>>8)]) + c2.s3[byte(xr2)] ^ c2.p[6]
	xl3 ^= ((c3.s0[byte(xr3>>24)] + c3.s1[byte(xr3>>16)]) ^ c3.s2[byte(xr3>>8)]) + c3.s3[byte(xr3)] ^ c3.p[6]
	xr0 ^= ((c0.s0[byte(xl0>>24)] + c0.s1[byte(xl0>>16)]) ^ c0.s2[byte(xl0>>8)]) + c0.s3[byte(xl0)] ^ c0.p[7]
	xr1 ^= ((c1.s0[byte(xl1>>24)] + c1.s1[byte(xl1>>16)]) ^ c1.s2[byte(xl1>>8)]) + c1.s3[byte(xl1)] ^ c1.p[7]
	xr2 ^= ((c2.s0[byte(xl2>>24)] + c2.s1[byte(xl2>>16)]) ^ c2.s2[byte(xl2>>8)]) + c2.s3[byte(xl2)] ^ c2.p[7]
	xr3 ^= ((c3.s0[byte(xl3>>24)] + c3.s1[byte(xl3>>16)]) ^ c3.s2[byte(xl3>>8)]) + c3.s3[byte(xl3)] ^ c3.p[7]
	xl0 ^= ((c0.s0[byte(xr0>>24)] + c0.s1[byte(xr0>>16)]) ^ c0.s2[byte(xr0>>8)]) + c0.s3[byte(xr0)] ^ c0.p[8]
	xl1 ^= ((c1.s0[byte(xr1>>24)] + c1.s1[byte(xr1>>16)]) ^ c1.s2[byte(xr1>>8)]) + c1.s3[byte(xr1)] ^ c1.p[8]
	xl2 ^= ((c2.s0[byte(xr2>>24)] + c2.s1[byte(xr2>>16)]) ^ c2.s2[byte(xr2>>8)]) + c2.s3[byte(xr2)] ^ c2.p[8]
	xl3 ^= ((c3.s0[byte(xr3>>24)] + c3.s1[byte(xr3>>16)]) ^ c3.s2[byte(xr3>>8)]) + c3.s3[byte(xr3)] ^ c3.p[8]
	xr0 ^= ((c0.s0[byte(xl0>>24)] + c0.s1[byte(xl0>>16)]) ^ c0.s2[byte(xl0>>8)]) + c0.s3[byte(xl0)] ^ c0.p[9]
	xr1 ^= ((c1.s0[byte(xl1>>24)] + c1.s1[byte(xl1>>16)]) ^ c1.s2[byte(xl1>>8)]) + c1.s3[byte(xl1)] ^ c1.p[9]
	xr2 ^= ((c2.s0[byte(xl2>>24)] + c2.s1[byte(xl2>>16)]) ^ c2.s2[byte(xl2>>8)]) + c2.s3[byte(xl2)] ^ c2.p[9]
	xr3 ^= ((c3.s0[byte(xl3>>24)] + c3.s1[byte(xl3>>16)]) ^ c3.s2[byte(xl3>>8)]) + c3.s3[byte(xl3)] ^ c3.p[9]
	xl0 ^= ((c0.s0[byte(xr0>>24)] + c0.s1[byte(xr0>>16)]) ^ c0.s2[byte(xr0>>8)]) + c0.s3[byte(xr0)] ^ c0.p[10]
	xl1 ^= ((c1.s0[byte(xr1>>24)] + c1.s1[byte(xr1>>16)]) ^ c1.s2[byte(xr1>>8)]) + c1.s3[byte(xr1)] ^ c1.p[10]
	xl2 ^= ((c2.s0[byte(xr2>>24)] + c2.s1[byte(xr2>>16)]) ^ c2.s2[byte(xr2>>8)]) + c2.s3[byte(xr2)] ^ c2.p[10]
	xl3 ^= ((c3.s0[byte(xr3>>24)] + c3.s1[byte(xr3>>16)]) ^ c3.s2[byte(xr3>>8)]) + c3.s3[byte(xr3)] ^ c3.p[10]
	xr0 ^= ((c0.s0[byte(xl0>>24)] + c0.s1[byte(xl0>>16)]) ^ c0.s2[byte(xl0>>8)]) + c0.s3[byte(xl0)] ^ c0.p[11]
	xr1 ^= ((c1.s0[byte(xl1>>24)] + c1.s1[byte(xl1>>16)]) ^ c1.s2[byte(xl1>>8)]) + c1.s3[byte(xl1)] ^ c1.p[11]
	xr2 ^= ((c2.s0[byte(xl2>>24)] + c2.s1[byte(xl2>>16)]) ^ c2.s2[byte(xl2>>8)]) + c2.s3[byte(xl2)] ^ c2.p[11]
	xr3 ^= ((c3.s0[byte(xl3>>24)] + c3.s1[byte(xl3>>16)]) ^ c3.s2[byte(xl3>>8)]) + c3.s3[byte(xl3)] ^ c3.p[11]
	xl0 ^= ((c0.s0[byte(xr0>>24)] + c0.s1[byte(xr0>>16)]) ^ c0.s2[byte(xr0>>8)]) + c0.s3[byte(xr0)] ^ c0.p[12]
	xl1 ^= ((c1.s0[byte(xr1>>24)] + c1.s1[byte(xr1>>16)]) ^ c1.s2[byte(xr1>>8)]) + c1.s3[byte(xr1)] ^ c1.p[12]
	xl2 ^= ((c2.s0[byte(xr2>>24)] + c2.s1[byte(xr2>>16)]) ^ c2.s2[byte(xr2>>8)]) + c2.s3[byte(xr2)] ^ c2.p[12]
	xl3 ^= ((c3.s0[byte(xr3>>24)] + c3.s1[byte(xr3>>16)]) ^ c3.s2[byte(xr3>>8)]) + c3.s3[byte(xr3)] ^ c3.p[12]
	xr0 ^= ((c0.s0[byte(xl0>>24)] + c0.s1[byte(xl0>>16)]) ^ c0.s2[byte(xl0>>8)]) + c0.s3[byte(xl0)] ^ c0.p[13]
	xr1 ^= ((c1.s0[byte(xl1>>24)] + c1.s1[byte(xl1>>16)]) ^ c1.s2[byte(xl1>>8)]) + c1.s3[byte(xl1)] ^ c1.p[13]
	xr2 ^= ((c2.s0[byte(xl2>>24)] + c2.s1[byte(xl2>>16)]) ^ c2.s2[byte(xl2>>8)]) + c2.s3[byte(xl2)] ^ c2.p[13]
	xr3 ^= ((c3.s0[byte(xl3>>24)] + c3.s1[byte(xl3>>16)]) ^ c3.s2[byte(xl3>>8)]) + c3.s3[byte(xl3)] ^ c3.p[13]
	xl0 ^= ((c0.s0[byte(xr0>>24)] + c0.s1[byte(xr0>>16)]) ^ c0.s2[byte(xr0>>8)]) + c0.s3[byte(xr0)] ^ c0.p[14]
	xl1 ^= ((c1.s0[byte(xr1>>24)] + c1.s1[byte(xr1>>16)]) ^ c1.s2[byte(xr1>>8)]) + c1.s3[byte(xr1)] ^ c1.p[14]
	xl2 ^= ((c2.s0[byte(xr2>>24)] + c2.s1[byte(xr2>>16)]) ^ c2.s2[byte(xr2>>8)]) + c2.s3[byte(xr2)] ^ c2.p[14]
	xl3 ^= ((c3.s0[byte(xr3>>24)] + c3.s1[byte(xr3>>16)]) ^ c3.s2[byte(xr3>>8)]) + c3.s3[byte(xr3)] ^ c3.p[14]
	xr0 ^= ((c0.s0[byte(xl0>>24)] + c0.s1[byte(xl0>>16)]) ^ c0.s2[byte(xl0>>8)]) + c0.s3[byte(xl0)] ^ c0.p[15]
	xr1 ^= ((c1.s0[byte(xl1>>24)] + c1.s1[byte(xl1>>16)]) ^ c1.s2[byte(xl1>>8)]) + c1.s3[byte(xl1)] ^ c1.p[15]
	xr2 ^= ((c2.s0[byte(xl2>>24)] + c2.s1[byte(xl2>>16)]) ^ c2.s2[byte(xl2>>8)]) + c2.s3[byte(xl2)] ^ c2.p[15]
	xr3 ^= ((c3.s0[byte(xl3>>24)] + c3.s1[byte(xl3>>16)]) ^ c3.s2[byte(xl3>>8)]) + c3.s3[byte(xl3)] ^ c3.p[15]
	xl0 ^= ((c0.s0[byte(xr0>>24)] + c0.s1[byte(xr0>>16)]) ^ c0.s2[byte(xr0>>8)]) + c0.s3[byte(xr0)] ^ c0.p[16]
	xl1 ^= ((c1.s0[byte(xr1>>24)] + c1.s1[byte(xr1>>16)]) ^ c1.s2[byte(xr1>>8)]) + c1.s3[byte(xr1)] ^ c1.p[16]
	xl2 ^= ((c2.s0[byte(xr2>>24)] + c2.s1[byte(xr2>>16)]) ^ c2.s2[byte(xr2>>8)]) + c2.s3[byte(xr2)] ^ c2.p[16]
	xl3 ^= ((c3.s0[byte(xr3>>24)] + c3.s1[byte(xr3>>16)]) ^ c3.s2[byte(xr3>>8)]) + c3.s3[byte(xr3)] ^ c3.p[16]
	xr0 ^= c0.p[17]
	xr1 ^= c1.p[17]
	xr2 ^= c2.p[17]
	xr3 ^= c3.p[17]
	return xr0, xl0, xr1, xl1, xr2, xl2, xr3, xl3
}

func expandKey4(keys [4][]byte, c [4]*state) {
	for i := 0; i < 18; i++ {
		c[0].p[i] ^= nextWord(keys[0], i*4)
		c[1].p[i] ^= nextWord(keys[1], i*4)
		c[2].p[i] ^= nextWord(keys[2], i*4)
		c[3].p[i] ^= nextWord(keys[3], i*4)
	}
	c0 := c[0]
	c1 := c[1]
	c2 := c[2]
	c3 := c[3]
	var l0, r0 uint32
	var l1, r1 uint32
	var l2, r2 uint32
	var l3, r3 uint32
	for i := 0; i < 18; i += 2 {
		l0, r0, l1, r1, l2, r2, l3, r3 = encryptBlock4(l0, r0, l1, r1, l2, r2, l3, r3, c0, c1, c2, c3)
		c0.p[i], c0.p[i+1] = l0, r0
		c1.p[i], c1.p[i+1] = l1, r1
		c2.p[i], c2.p[i+1] = l2, r2
		c3.p[i], c3.p[i+1] = l3, r3
	}
	for i := 0; i < 256; i += 2 {
		l0, r0, l1, r1, l2, r2, l3, r3 = encryptBlock4(l0, r0, l1, r1, l2, r2, l3, r3, c0, c1, c2, c3)
		c0.s0[i], c0.s0[i+1] = l0, r0
		c1.s0[i], c1.s0[i+1] = l1, r1
		c2.s0[i], c2.s0[i+1] = l2, r2
		c3.s0[i], c3.s0[i+1] = l3, r3
	}
	for i := 0; i < 256; i += 2 {
		l0, r0, l1, r1, l2, r2, l3, r3 = encryptBlock4(l0, r0, l1, r1, l2, r2, l3, r3, c0, c1, c2, c3)
		c0.s1[i], c0.s1[i+1] = l0, r0
		c1.s1[i], c1.s1[i+1] = l1, r1
		c2.s1[i], c2.s1[i+1] = l2, r2
		c3.s1[i], c3.s1[i+1] = l3, r3
	}
	for i := 0; i < 256; i += 2 {
		l0, r0, l1, r1, l2, r2, l3, r3 = encryptBlock4(l0, r0, l1, r1, l2, r2, l3, r3, c0, c1, c2, c3)
		c0.s2[i], c0.s2[i+1] = l0, r0
		c1.s2[i], c1.s2[i+1] = l1, r1
		c2.s2[i], c2.s2[i+1] = l2, r2
		c3.s2[i], c3.s2[i+1] = l3, r3
	}
	for i := 0; i < 256; i += 2 {
		l0, r0, l1, r1, l2, r2, l3, r3 = encryptBlock4(l0, r0, l1, r1, l2, r2, l3, r3, c0, c1, c2, c3)
		c0.s3[i], c0.s3[i+1] = l0, r0
		c1.s3[i], c1.s3[i+1] = l1, r1
		c2.s3[i], c2.s3[i+1] = l2, r2
		c3.s3[i], c3.s3[i+1] = l3, r3
	}
}

func expandKeyWithSalt4(keys [4][]byte, salt []byte, c [4]*state) {
	for i := 0; i < 18; i++ {
		c[0].p[i] ^= nextWord(keys[0], i*4)
		c[1].p[i] ^= nextWord(keys[1], i*4)
		c[2].p[i] ^= nextWord(keys[2], i*4)
		c[3].p[i] ^= nextWord(keys[3], i*4)
	}
	c0 := c[0]
	c1 := c[1]
	c2 := c[2]
	c3 := c[3]
	var l0, r0 uint32
	var l1, r1 uint32
	var l2, r2 uint32
	var l3, r3 uint32
	sj := 0
	for i := 0; i < 18; i += 2 {
		l0 ^= saltWord(salt, sj)
		r0 ^= saltWord(salt, sj+4)
		l1 ^= saltWord(salt, sj)
		r1 ^= saltWord(salt, sj+4)
		l2 ^= saltWord(salt, sj)
		r2 ^= saltWord(salt, sj+4)
		l3 ^= saltWord(salt, sj)
		r3 ^= saltWord(salt, sj+4)
		sj = (sj + 8) % len(salt)
		l0, r0, l1, r1, l2, r2, l3, r3 = encryptBlock4(l0, r0, l1, r1, l2, r2, l3, r3, c0, c1, c2, c3)
		c0.p[i], c0.p[i+1] = l0, r0
		c1.p[i], c1.p[i+1] = l1, r1
		c2.p[i], c2.p[i+1] = l2, r2
		c3.p[i], c3.p[i+1] = l3, r3
	}
	for i := 0; i < 256; i += 2 {
		l0 ^= saltWord(salt, sj)
		r0 ^= saltWord(salt, sj+4)
		l1 ^= saltWord(salt, sj)
		r1 ^= saltWord(salt, sj+4)
		l2 ^= saltWord(salt, sj)
		r2 ^= saltWord(salt, sj+4)
		l3 ^= saltWord(salt, sj)
		r3 ^= saltWord(salt, sj+4)
		sj = (sj + 8) % len(salt)
		l0, r0, l1, r1, l2, r2, l3, r3 = encryptBlock4(l0, r0, l1, r1, l2, r2, l3, r3, c0, c1, c2, c3)
		c0.s0[i], c0.s0[i+1] = l0, r0
		c1.s0[i], c1.s0[i+1] = l1, r1
		c2.s0[i], c2.s0[i+1] = l2, r2
		c3.s0[i], c3.s0[i+1] = l3, r3
	}
	for i := 0; i < 256; i += 2 {
		l0 ^= saltWord(salt, sj)
		r0 ^= saltWord(salt, sj+4)
		l1 ^= saltWord(salt, sj)
		r1 ^= saltWord(salt, sj+4)
		l2 ^= saltWord(salt, sj)
		r2 ^= saltWord(salt, sj+4)
		l3 ^= saltWord(salt, sj)
		r3 ^= saltWord(salt, sj+4)
		sj = (sj + 8) % len(salt)
		l0, r0, l1, r1, l2, r2, l3, r3 = encryptBlock4(l0, r0, l1, r1, l2, r2, l3, r3, c0, c1, c2, c3)
		c0.s1[i], c0.s1[i+1] = l0, r0
		c1.s1[i], c1.s1[i+1] = l1, r1
		c2.s1[i], c2.s1[i+1] = l2, r2
		c3.s1[i], c3.s1[i+1] = l3, r3
	}
	for i := 0; i < 256; i += 2 {
		l0 ^= saltWord(salt, sj)
		r0 ^= saltWord(salt, sj+4)
		l1 ^= saltWord(salt, sj)
		r1 ^= saltWord(salt, sj+4)
		l2 ^= saltWord(salt, sj)
		r2 ^= saltWord(salt, sj+4)
		l3 ^= saltWord(salt, sj)
		r3 ^= saltWord(salt, sj+4)
		sj = (sj + 8) % len(salt)
		l0, r0, l1, r1, l2, r2, l3, r3 = encryptBlock4(l0, r0, l1, r1, l2, r2, l3, r3, c0, c1, c2, c3)
		c0.s2[i], c0.s2[i+1] = l0, r0
		c1.s2[i], c1.s2[i+1] = l1, r1
		c2.s2[i], c2.s2[i+1] = l2, r2
		c3.s2[i], c3.s2[i+1] = l3, r3
	}
	for i := 0; i < 256; i += 2 {
		l0 ^= saltWord(salt, sj)
		r0 ^= saltWord(salt, sj+4)
		l1 ^= saltWord(salt, sj)
		r1 ^= saltWord(salt, sj+4)
		l2 ^= saltWord(salt, sj)
		r2 ^= saltWord(salt, sj+4)
		l3 ^= saltWord(salt, sj)
		r3 ^= saltWord(salt, sj+4)
		sj = (sj + 8) % len(salt)
		l0, r0, l1, r1, l2, r2, l3, r3 = encryptBlock4(l0, r0, l1, r1, l2, r2, l3, r3, c0, c1, c2, c3)
		c0.s3[i], c0.s3[i+1] = l0, r0
		c1.s3[i], c1.s3[i+1] = l1, r1
		c2.s3[i], c2.s3[i+1] = l2, r2
		c3.s3[i], c3.s3[i+1] = l3, r3
	}
}

// run4 hashes exactly 4 candidates through interleaved lanes,
// writing verdicts to h.verdicts[:4].
func (h *Hasher) run4(pw [][]byte) {
	var keys [4][]byte
	var c [4]*state
	for i := 0; i < 4; i++ {
		// bug compatibility: the key's trailing NUL participates
		k := append(h.keyScratch[i][:0], pw[i]...)
		k = append(k, 0)
		h.keyScratch[i] = k
		keys[i] = k
		// no zeroing: initState overwrites p and s0..s3 in full;
		// clearing 4 KB per lane per batch would be pure waste.
		c[i] = &h.scratch[i]
		initState(c[i])
	}
	salt := h.csalt[:]
	expandKeyWithSalt4(keys, salt, c)
	var saltKeys [4][]byte
	for i := 0; i < 4; i++ {
		saltKeys[i] = salt
	}
	for r, rounds := uint64(0), uint64(1)<<uint(h.cost); r < rounds; r++ {
		expandKey4(keys, c)
		expandKey4(saltKeys, c)
	}
	for i := 0; i < 4; i++ {
		h.verdicts[i] = h.finish(c[i])
	}
}

func encryptBlock8(l0, r0 uint32, l1, r1 uint32, l2, r2 uint32, l3, r3 uint32, l4, r4 uint32, l5, r5 uint32, l6, r6 uint32, l7, r7 uint32, c0 *state, c1 *state, c2 *state, c3 *state, c4 *state, c5 *state, c6 *state, c7 *state) (uint32, uint32, uint32, uint32, uint32, uint32, uint32, uint32, uint32, uint32, uint32, uint32, uint32, uint32, uint32, uint32) {
	xl0, xr0 := l0, r0
	xl1, xr1 := l1, r1
	xl2, xr2 := l2, r2
	xl3, xr3 := l3, r3
	xl4, xr4 := l4, r4
	xl5, xr5 := l5, r5
	xl6, xr6 := l6, r6
	xl7, xr7 := l7, r7
	xl0 ^= c0.p[0]
	xl1 ^= c1.p[0]
	xl2 ^= c2.p[0]
	xl3 ^= c3.p[0]
	xl4 ^= c4.p[0]
	xl5 ^= c5.p[0]
	xl6 ^= c6.p[0]
	xl7 ^= c7.p[0]
	xr0 ^= ((c0.s0[byte(xl0>>24)] + c0.s1[byte(xl0>>16)]) ^ c0.s2[byte(xl0>>8)]) + c0.s3[byte(xl0)] ^ c0.p[1]
	xr1 ^= ((c1.s0[byte(xl1>>24)] + c1.s1[byte(xl1>>16)]) ^ c1.s2[byte(xl1>>8)]) + c1.s3[byte(xl1)] ^ c1.p[1]
	xr2 ^= ((c2.s0[byte(xl2>>24)] + c2.s1[byte(xl2>>16)]) ^ c2.s2[byte(xl2>>8)]) + c2.s3[byte(xl2)] ^ c2.p[1]
	xr3 ^= ((c3.s0[byte(xl3>>24)] + c3.s1[byte(xl3>>16)]) ^ c3.s2[byte(xl3>>8)]) + c3.s3[byte(xl3)] ^ c3.p[1]
	xr4 ^= ((c4.s0[byte(xl4>>24)] + c4.s1[byte(xl4>>16)]) ^ c4.s2[byte(xl4>>8)]) + c4.s3[byte(xl4)] ^ c4.p[1]
	xr5 ^= ((c5.s0[byte(xl5>>24)] + c5.s1[byte(xl5>>16)]) ^ c5.s2[byte(xl5>>8)]) + c5.s3[byte(xl5)] ^ c5.p[1]
	xr6 ^= ((c6.s0[byte(xl6>>24)] + c6.s1[byte(xl6>>16)]) ^ c6.s2[byte(xl6>>8)]) + c6.s3[byte(xl6)] ^ c6.p[1]
	xr7 ^= ((c7.s0[byte(xl7>>24)] + c7.s1[byte(xl7>>16)]) ^ c7.s2[byte(xl7>>8)]) + c7.s3[byte(xl7)] ^ c7.p[1]
	xl0 ^= ((c0.s0[byte(xr0>>24)] + c0.s1[byte(xr0>>16)]) ^ c0.s2[byte(xr0>>8)]) + c0.s3[byte(xr0)] ^ c0.p[2]
	xl1 ^= ((c1.s0[byte(xr1>>24)] + c1.s1[byte(xr1>>16)]) ^ c1.s2[byte(xr1>>8)]) + c1.s3[byte(xr1)] ^ c1.p[2]
	xl2 ^= ((c2.s0[byte(xr2>>24)] + c2.s1[byte(xr2>>16)]) ^ c2.s2[byte(xr2>>8)]) + c2.s3[byte(xr2)] ^ c2.p[2]
	xl3 ^= ((c3.s0[byte(xr3>>24)] + c3.s1[byte(xr3>>16)]) ^ c3.s2[byte(xr3>>8)]) + c3.s3[byte(xr3)] ^ c3.p[2]
	xl4 ^= ((c4.s0[byte(xr4>>24)] + c4.s1[byte(xr4>>16)]) ^ c4.s2[byte(xr4>>8)]) + c4.s3[byte(xr4)] ^ c4.p[2]
	xl5 ^= ((c5.s0[byte(xr5>>24)] + c5.s1[byte(xr5>>16)]) ^ c5.s2[byte(xr5>>8)]) + c5.s3[byte(xr5)] ^ c5.p[2]
	xl6 ^= ((c6.s0[byte(xr6>>24)] + c6.s1[byte(xr6>>16)]) ^ c6.s2[byte(xr6>>8)]) + c6.s3[byte(xr6)] ^ c6.p[2]
	xl7 ^= ((c7.s0[byte(xr7>>24)] + c7.s1[byte(xr7>>16)]) ^ c7.s2[byte(xr7>>8)]) + c7.s3[byte(xr7)] ^ c7.p[2]
	xr0 ^= ((c0.s0[byte(xl0>>24)] + c0.s1[byte(xl0>>16)]) ^ c0.s2[byte(xl0>>8)]) + c0.s3[byte(xl0)] ^ c0.p[3]
	xr1 ^= ((c1.s0[byte(xl1>>24)] + c1.s1[byte(xl1>>16)]) ^ c1.s2[byte(xl1>>8)]) + c1.s3[byte(xl1)] ^ c1.p[3]
	xr2 ^= ((c2.s0[byte(xl2>>24)] + c2.s1[byte(xl2>>16)]) ^ c2.s2[byte(xl2>>8)]) + c2.s3[byte(xl2)] ^ c2.p[3]
	xr3 ^= ((c3.s0[byte(xl3>>24)] + c3.s1[byte(xl3>>16)]) ^ c3.s2[byte(xl3>>8)]) + c3.s3[byte(xl3)] ^ c3.p[3]
	xr4 ^= ((c4.s0[byte(xl4>>24)] + c4.s1[byte(xl4>>16)]) ^ c4.s2[byte(xl4>>8)]) + c4.s3[byte(xl4)] ^ c4.p[3]
	xr5 ^= ((c5.s0[byte(xl5>>24)] + c5.s1[byte(xl5>>16)]) ^ c5.s2[byte(xl5>>8)]) + c5.s3[byte(xl5)] ^ c5.p[3]
	xr6 ^= ((c6.s0[byte(xl6>>24)] + c6.s1[byte(xl6>>16)]) ^ c6.s2[byte(xl6>>8)]) + c6.s3[byte(xl6)] ^ c6.p[3]
	xr7 ^= ((c7.s0[byte(xl7>>24)] + c7.s1[byte(xl7>>16)]) ^ c7.s2[byte(xl7>>8)]) + c7.s3[byte(xl7)] ^ c7.p[3]
	xl0 ^= ((c0.s0[byte(xr0>>24)] + c0.s1[byte(xr0>>16)]) ^ c0.s2[byte(xr0>>8)]) + c0.s3[byte(xr0)] ^ c0.p[4]
	xl1 ^= ((c1.s0[byte(xr1>>24)] + c1.s1[byte(xr1>>16)]) ^ c1.s2[byte(xr1>>8)]) + c1.s3[byte(xr1)] ^ c1.p[4]
	xl2 ^= ((c2.s0[byte(xr2>>24)] + c2.s1[byte(xr2>>16)]) ^ c2.s2[byte(xr2>>8)]) + c2.s3[byte(xr2)] ^ c2.p[4]
	xl3 ^= ((c3.s0[byte(xr3>>24)] + c3.s1[byte(xr3>>16)]) ^ c3.s2[byte(xr3>>8)]) + c3.s3[byte(xr3)] ^ c3.p[4]
	xl4 ^= ((c4.s0[byte(xr4>>24)] + c4.s1[byte(xr4>>16)]) ^ c4.s2[byte(xr4>>8)]) + c4.s3[byte(xr4)] ^ c4.p[4]
	xl5 ^= ((c5.s0[byte(xr5>>24)] + c5.s1[byte(xr5>>16)]) ^ c5.s2[byte(xr5>>8)]) + c5.s3[byte(xr5)] ^ c5.p[4]
	xl6 ^= ((c6.s0[byte(xr6>>24)] + c6.s1[byte(xr6>>16)]) ^ c6.s2[byte(xr6>>8)]) + c6.s3[byte(xr6)] ^ c6.p[4]
	xl7 ^= ((c7.s0[byte(xr7>>24)] + c7.s1[byte(xr7>>16)]) ^ c7.s2[byte(xr7>>8)]) + c7.s3[byte(xr7)] ^ c7.p[4]
	xr0 ^= ((c0.s0[byte(xl0>>24)] + c0.s1[byte(xl0>>16)]) ^ c0.s2[byte(xl0>>8)]) + c0.s3[byte(xl0)] ^ c0.p[5]
	xr1 ^= ((c1.s0[byte(xl1>>24)] + c1.s1[byte(xl1>>16)]) ^ c1.s2[byte(xl1>>8)]) + c1.s3[byte(xl1)] ^ c1.p[5]
	xr2 ^= ((c2.s0[byte(xl2>>24)] + c2.s1[byte(xl2>>16)]) ^ c2.s2[byte(xl2>>8)]) + c2.s3[byte(xl2)] ^ c2.p[5]
	xr3 ^= ((c3.s0[byte(xl3>>24)] + c3.s1[byte(xl3>>16)]) ^ c3.s2[byte(xl3>>8)]) + c3.s3[byte(xl3)] ^ c3.p[5]
	xr4 ^= ((c4.s0[byte(xl4>>24)] + c4.s1[byte(xl4>>16)]) ^ c4.s2[byte(xl4>>8)]) + c4.s3[byte(xl4)] ^ c4.p[5]
	xr5 ^= ((c5.s0[byte(xl5>>24)] + c5.s1[byte(xl5>>16)]) ^ c5.s2[byte(xl5>>8)]) + c5.s3[byte(xl5)] ^ c5.p[5]
	xr6 ^= ((c6.s0[byte(xl6>>24)] + c6.s1[byte(xl6>>16)]) ^ c6.s2[byte(xl6>>8)]) + c6.s3[byte(xl6)] ^ c6.p[5]
	xr7 ^= ((c7.s0[byte(xl7>>24)] + c7.s1[byte(xl7>>16)]) ^ c7.s2[byte(xl7>>8)]) + c7.s3[byte(xl7)] ^ c7.p[5]
	xl0 ^= ((c0.s0[byte(xr0>>24)] + c0.s1[byte(xr0>>16)]) ^ c0.s2[byte(xr0>>8)]) + c0.s3[byte(xr0)] ^ c0.p[6]
	xl1 ^= ((c1.s0[byte(xr1>>24)] + c1.s1[byte(xr1>>16)]) ^ c1.s2[byte(xr1>>8)]) + c1.s3[byte(xr1)] ^ c1.p[6]
	xl2 ^= ((c2.s0[byte(xr2>>24)] + c2.s1[byte(xr2>>16)]) ^ c2.s2[byte(xr2>>8)]) + c2.s3[byte(xr2)] ^ c2.p[6]
	xl3 ^= ((c3.s0[byte(xr3>>24)] + c3.s1[byte(xr3>>16)]) ^ c3.s2[byte(xr3>>8)]) + c3.s3[byte(xr3)] ^ c3.p[6]
	xl4 ^= ((c4.s0[byte(xr4>>24)] + c4.s1[byte(xr4>>16)]) ^ c4.s2[byte(xr4>>8)]) + c4.s3[byte(xr4)] ^ c4.p[6]
	xl5 ^= ((c5.s0[byte(xr5>>24)] + c5.s1[byte(xr5>>16)]) ^ c5.s2[byte(xr5>>8)]) + c5.s3[byte(xr5)] ^ c5.p[6]
	xl6 ^= ((c6.s0[byte(xr6>>24)] + c6.s1[byte(xr6>>16)]) ^ c6.s2[byte(xr6>>8)]) + c6.s3[byte(xr6)] ^ c6.p[6]
	xl7 ^= ((c7.s0[byte(xr7>>24)] + c7.s1[byte(xr7>>16)]) ^ c7.s2[byte(xr7>>8)]) + c7.s3[byte(xr7)] ^ c7.p[6]
	xr0 ^= ((c0.s0[byte(xl0>>24)] + c0.s1[byte(xl0>>16)]) ^ c0.s2[byte(xl0>>8)]) + c0.s3[byte(xl0)] ^ c0.p[7]
	xr1 ^= ((c1.s0[byte(xl1>>24)] + c1.s1[byte(xl1>>16)]) ^ c1.s2[byte(xl1>>8)]) + c1.s3[byte(xl1)] ^ c1.p[7]
	xr2 ^= ((c2.s0[byte(xl2>>24)] + c2.s1[byte(xl2>>16)]) ^ c2.s2[byte(xl2>>8)]) + c2.s3[byte(xl2)] ^ c2.p[7]
	xr3 ^= ((c3.s0[byte(xl3>>24)] + c3.s1[byte(xl3>>16)]) ^ c3.s2[byte(xl3>>8)]) + c3.s3[byte(xl3)] ^ c3.p[7]
	xr4 ^= ((c4.s0[byte(xl4>>24)] + c4.s1[byte(xl4>>16)]) ^ c4.s2[byte(xl4>>8)]) + c4.s3[byte(xl4)] ^ c4.p[7]
	xr5 ^= ((c5.s0[byte(xl5>>24)] + c5.s1[byte(xl5>>16)]) ^ c5.s2[byte(xl5>>8)]) + c5.s3[byte(xl5)] ^ c5.p[7]
	xr6 ^= ((c6.s0[byte(xl6>>24)] + c6.s1[byte(xl6>>16)]) ^ c6.s2[byte(xl6>>8)]) + c6.s3[byte(xl6)] ^ c6.p[7]
	xr7 ^= ((c7.s0[byte(xl7>>24)] + c7.s1[byte(xl7>>16)]) ^ c7.s2[byte(xl7>>8)]) + c7.s3[byte(xl7)] ^ c7.p[7]
	xl0 ^= ((c0.s0[byte(xr0>>24)] + c0.s1[byte(xr0>>16)]) ^ c0.s2[byte(xr0>>8)]) + c0.s3[byte(xr0)] ^ c0.p[8]
	xl1 ^= ((c1.s0[byte(xr1>>24)] + c1.s1[byte(xr1>>16)]) ^ c1.s2[byte(xr1>>8)]) + c1.s3[byte(xr1)] ^ c1.p[8]
	xl2 ^= ((c2.s0[byte(xr2>>24)] + c2.s1[byte(xr2>>16)]) ^ c2.s2[byte(xr2>>8)]) + c2.s3[byte(xr2)] ^ c2.p[8]
	xl3 ^= ((c3.s0[byte(xr3>>24)] + c3.s1[byte(xr3>>16)]) ^ c3.s2[byte(xr3>>8)]) + c3.s3[byte(xr3)] ^ c3.p[8]
	xl4 ^= ((c4.s0[byte(xr4>>24)] + c4.s1[byte(xr4>>16)]) ^ c4.s2[byte(xr4>>8)]) + c4.s3[byte(xr4)] ^ c4.p[8]
	xl5 ^= ((c5.s0[byte(xr5>>24)] + c5.s1[byte(xr5>>16)]) ^ c5.s2[byte(xr5>>8)]) + c5.s3[byte(xr5)] ^ c5.p[8]
	xl6 ^= ((c6.s0[byte(xr6>>24)] + c6.s1[byte(xr6>>16)]) ^ c6.s2[byte(xr6>>8)]) + c6.s3[byte(xr6)] ^ c6.p[8]
	xl7 ^= ((c7.s0[byte(xr7>>24)] + c7.s1[byte(xr7>>16)]) ^ c7.s2[byte(xr7>>8)]) + c7.s3[byte(xr7)] ^ c7.p[8]
	xr0 ^= ((c0.s0[byte(xl0>>24)] + c0.s1[byte(xl0>>16)]) ^ c0.s2[byte(xl0>>8)]) + c0.s3[byte(xl0)] ^ c0.p[9]
	xr1 ^= ((c1.s0[byte(xl1>>24)] + c1.s1[byte(xl1>>16)]) ^ c1.s2[byte(xl1>>8)]) + c1.s3[byte(xl1)] ^ c1.p[9]
	xr2 ^= ((c2.s0[byte(xl2>>24)] + c2.s1[byte(xl2>>16)]) ^ c2.s2[byte(xl2>>8)]) + c2.s3[byte(xl2)] ^ c2.p[9]
	xr3 ^= ((c3.s0[byte(xl3>>24)] + c3.s1[byte(xl3>>16)]) ^ c3.s2[byte(xl3>>8)]) + c3.s3[byte(xl3)] ^ c3.p[9]
	xr4 ^= ((c4.s0[byte(xl4>>24)] + c4.s1[byte(xl4>>16)]) ^ c4.s2[byte(xl4>>8)]) + c4.s3[byte(xl4)] ^ c4.p[9]
	xr5 ^= ((c5.s0[byte(xl5>>24)] + c5.s1[byte(xl5>>16)]) ^ c5.s2[byte(xl5>>8)]) + c5.s3[byte(xl5)] ^ c5.p[9]
	xr6 ^= ((c6.s0[byte(xl6>>24)] + c6.s1[byte(xl6>>16)]) ^ c6.s2[byte(xl6>>8)]) + c6.s3[byte(xl6)] ^ c6.p[9]
	xr7 ^= ((c7.s0[byte(xl7>>24)] + c7.s1[byte(xl7>>16)]) ^ c7.s2[byte(xl7>>8)]) + c7.s3[byte(xl7)] ^ c7.p[9]
	xl0 ^= ((c0.s0[byte(xr0>>24)] + c0.s1[byte(xr0>>16)]) ^ c0.s2[byte(xr0>>8)]) + c0.s3[byte(xr0)] ^ c0.p[10]
	xl1 ^= ((c1.s0[byte(xr1>>24)] + c1.s1[byte(xr1>>16)]) ^ c1.s2[byte(xr1>>8)]) + c1.s3[byte(xr1)] ^ c1.p[10]
	xl2 ^= ((c2.s0[byte(xr2>>24)] + c2.s1[byte(xr2>>16)]) ^ c2.s2[byte(xr2>>8)]) + c2.s3[byte(xr2)] ^ c2.p[10]
	xl3 ^= ((c3.s0[byte(xr3>>24)] + c3.s1[byte(xr3>>16)]) ^ c3.s2[byte(xr3>>8)]) + c3.s3[byte(xr3)] ^ c3.p[10]
	xl4 ^= ((c4.s0[byte(xr4>>24)] + c4.s1[byte(xr4>>16)]) ^ c4.s2[byte(xr4>>8)]) + c4.s3[byte(xr4)] ^ c4.p[10]
	xl5 ^= ((c5.s0[byte(xr5>>24)] + c5.s1[byte(xr5>>16)]) ^ c5.s2[byte(xr5>>8)]) + c5.s3[byte(xr5)] ^ c5.p[10]
	xl6 ^= ((c6.s0[byte(xr6>>24)] + c6.s1[byte(xr6>>16)]) ^ c6.s2[byte(xr6>>8)]) + c6.s3[byte(xr6)] ^ c6.p[10]
	xl7 ^= ((c7.s0[byte(xr7>>24)] + c7.s1[byte(xr7>>16)]) ^ c7.s2[byte(xr7>>8)]) + c7.s3[byte(xr7)] ^ c7.p[10]
	xr0 ^= ((c0.s0[byte(xl0>>24)] + c0.s1[byte(xl0>>16)]) ^ c0.s2[byte(xl0>>8)]) + c0.s3[byte(xl0)] ^ c0.p[11]
	xr1 ^= ((c1.s0[byte(xl1>>24)] + c1.s1[byte(xl1>>16)]) ^ c1.s2[byte(xl1>>8)]) + c1.s3[byte(xl1)] ^ c1.p[11]
	xr2 ^= ((c2.s0[byte(xl2>>24)] + c2.s1[byte(xl2>>16)]) ^ c2.s2[byte(xl2>>8)]) + c2.s3[byte(xl2)] ^ c2.p[11]
	xr3 ^= ((c3.s0[byte(xl3>>24)] + c3.s1[byte(xl3>>16)]) ^ c3.s2[byte(xl3>>8)]) + c3.s3[byte(xl3)] ^ c3.p[11]
	xr4 ^= ((c4.s0[byte(xl4>>24)] + c4.s1[byte(xl4>>16)]) ^ c4.s2[byte(xl4>>8)]) + c4.s3[byte(xl4)] ^ c4.p[11]
	xr5 ^= ((c5.s0[byte(xl5>>24)] + c5.s1[byte(xl5>>16)]) ^ c5.s2[byte(xl5>>8)]) + c5.s3[byte(xl5)] ^ c5.p[11]
	xr6 ^= ((c6.s0[byte(xl6>>24)] + c6.s1[byte(xl6>>16)]) ^ c6.s2[byte(xl6>>8)]) + c6.s3[byte(xl6)] ^ c6.p[11]
	xr7 ^= ((c7.s0[byte(xl7>>24)] + c7.s1[byte(xl7>>16)]) ^ c7.s2[byte(xl7>>8)]) + c7.s3[byte(xl7)] ^ c7.p[11]
	xl0 ^= ((c0.s0[byte(xr0>>24)] + c0.s1[byte(xr0>>16)]) ^ c0.s2[byte(xr0>>8)]) + c0.s3[byte(xr0)] ^ c0.p[12]
	xl1 ^= ((c1.s0[byte(xr1>>24)] + c1.s1[byte(xr1>>16)]) ^ c1.s2[byte(xr1>>8)]) + c1.s3[byte(xr1)] ^ c1.p[12]
	xl2 ^= ((c2.s0[byte(xr2>>24)] + c2.s1[byte(xr2>>16)]) ^ c2.s2[byte(xr2>>8)]) + c2.s3[byte(xr2)] ^ c2.p[12]
	xl3 ^= ((c3.s0[byte(xr3>>24)] + c3.s1[byte(xr3>>16)]) ^ c3.s2[byte(xr3>>8)]) + c3.s3[byte(xr3)] ^ c3.p[12]
	xl4 ^= ((c4.s0[byte(xr4>>24)] + c4.s1[byte(xr4>>16)]) ^ c4.s2[byte(xr4>>8)]) + c4.s3[byte(xr4)] ^ c4.p[12]
	xl5 ^= ((c5.s0[byte(xr5>>24)] + c5.s1[byte(xr5>>16)]) ^ c5.s2[byte(xr5>>8)]) + c5.s3[byte(xr5)] ^ c5.p[12]
	xl6 ^= ((c6.s0[byte(xr6>>24)] + c6.s1[byte(xr6>>16)]) ^ c6.s2[byte(xr6>>8)]) + c6.s3[byte(xr6)] ^ c6.p[12]
	xl7 ^= ((c7.s0[byte(xr7>>24)] + c7.s1[byte(xr7>>16)]) ^ c7.s2[byte(xr7>>8)]) + c7.s3[byte(xr7)] ^ c7.p[12]
	xr0 ^= ((c0.s0[byte(xl0>>24)] + c0.s1[byte(xl0>>16)]) ^ c0.s2[byte(xl0>>8)]) + c0.s3[byte(xl0)] ^ c0.p[13]
	xr1 ^= ((c1.s0[byte(xl1>>24)] + c1.s1[byte(xl1>>16)]) ^ c1.s2[byte(xl1>>8)]) + c1.s3[byte(xl1)] ^ c1.p[13]
	xr2 ^= ((c2.s0[byte(xl2>>24)] + c2.s1[byte(xl2>>16)]) ^ c2.s2[byte(xl2>>8)]) + c2.s3[byte(xl2)] ^ c2.p[13]
	xr3 ^= ((c3.s0[byte(xl3>>24)] + c3.s1[byte(xl3>>16)]) ^ c3.s2[byte(xl3>>8)]) + c3.s3[byte(xl3)] ^ c3.p[13]
	xr4 ^= ((c4.s0[byte(xl4>>24)] + c4.s1[byte(xl4>>16)]) ^ c4.s2[byte(xl4>>8)]) + c4.s3[byte(xl4)] ^ c4.p[13]
	xr5 ^= ((c5.s0[byte(xl5>>24)] + c5.s1[byte(xl5>>16)]) ^ c5.s2[byte(xl5>>8)]) + c5.s3[byte(xl5)] ^ c5.p[13]
	xr6 ^= ((c6.s0[byte(xl6>>24)] + c6.s1[byte(xl6>>16)]) ^ c6.s2[byte(xl6>>8)]) + c6.s3[byte(xl6)] ^ c6.p[13]
	xr7 ^= ((c7.s0[byte(xl7>>24)] + c7.s1[byte(xl7>>16)]) ^ c7.s2[byte(xl7>>8)]) + c7.s3[byte(xl7)] ^ c7.p[13]
	xl0 ^= ((c0.s0[byte(xr0>>24)] + c0.s1[byte(xr0>>16)]) ^ c0.s2[byte(xr0>>8)]) + c0.s3[byte(xr0)] ^ c0.p[14]
	xl1 ^= ((c1.s0[byte(xr1>>24)] + c1.s1[byte(xr1>>16)]) ^ c1.s2[byte(xr1>>8)]) + c1.s3[byte(xr1)] ^ c1.p[14]
	xl2 ^= ((c2.s0[byte(xr2>>24)] + c2.s1[byte(xr2>>16)]) ^ c2.s2[byte(xr2>>8)]) + c2.s3[byte(xr2)] ^ c2.p[14]
	xl3 ^= ((c3.s0[byte(xr3>>24)] + c3.s1[byte(xr3>>16)]) ^ c3.s2[byte(xr3>>8)]) + c3.s3[byte(xr3)] ^ c3.p[14]
	xl4 ^= ((c4.s0[byte(xr4>>24)] + c4.s1[byte(xr4>>16)]) ^ c4.s2[byte(xr4>>8)]) + c4.s3[byte(xr4)] ^ c4.p[14]
	xl5 ^= ((c5.s0[byte(xr5>>24)] + c5.s1[byte(xr5>>16)]) ^ c5.s2[byte(xr5>>8)]) + c5.s3[byte(xr5)] ^ c5.p[14]
	xl6 ^= ((c6.s0[byte(xr6>>24)] + c6.s1[byte(xr6>>16)]) ^ c6.s2[byte(xr6>>8)]) + c6.s3[byte(xr6)] ^ c6.p[14]
	xl7 ^= ((c7.s0[byte(xr7>>24)] + c7.s1[byte(xr7>>16)]) ^ c7.s2[byte(xr7>>8)]) + c7.s3[byte(xr7)] ^ c7.p[14]
	xr0 ^= ((c0.s0[byte(xl0>>24)] + c0.s1[byte(xl0>>16)]) ^ c0.s2[byte(xl0>>8)]) + c0.s3[byte(xl0)] ^ c0.p[15]
	xr1 ^= ((c1.s0[byte(xl1>>24)] + c1.s1[byte(xl1>>16)]) ^ c1.s2[byte(xl1>>8)]) + c1.s3[byte(xl1)] ^ c1.p[15]
	xr2 ^= ((c2.s0[byte(xl2>>24)] + c2.s1[byte(xl2>>16)]) ^ c2.s2[byte(xl2>>8)]) + c2.s3[byte(xl2)] ^ c2.p[15]
	xr3 ^= ((c3.s0[byte(xl3>>24)] + c3.s1[byte(xl3>>16)]) ^ c3.s2[byte(xl3>>8)]) + c3.s3[byte(xl3)] ^ c3.p[15]
	xr4 ^= ((c4.s0[byte(xl4>>24)] + c4.s1[byte(xl4>>16)]) ^ c4.s2[byte(xl4>>8)]) + c4.s3[byte(xl4)] ^ c4.p[15]
	xr5 ^= ((c5.s0[byte(xl5>>24)] + c5.s1[byte(xl5>>16)]) ^ c5.s2[byte(xl5>>8)]) + c5.s3[byte(xl5)] ^ c5.p[15]
	xr6 ^= ((c6.s0[byte(xl6>>24)] + c6.s1[byte(xl6>>16)]) ^ c6.s2[byte(xl6>>8)]) + c6.s3[byte(xl6)] ^ c6.p[15]
	xr7 ^= ((c7.s0[byte(xl7>>24)] + c7.s1[byte(xl7>>16)]) ^ c7.s2[byte(xl7>>8)]) + c7.s3[byte(xl7)] ^ c7.p[15]
	xl0 ^= ((c0.s0[byte(xr0>>24)] + c0.s1[byte(xr0>>16)]) ^ c0.s2[byte(xr0>>8)]) + c0.s3[byte(xr0)] ^ c0.p[16]
	xl1 ^= ((c1.s0[byte(xr1>>24)] + c1.s1[byte(xr1>>16)]) ^ c1.s2[byte(xr1>>8)]) + c1.s3[byte(xr1)] ^ c1.p[16]
	xl2 ^= ((c2.s0[byte(xr2>>24)] + c2.s1[byte(xr2>>16)]) ^ c2.s2[byte(xr2>>8)]) + c2.s3[byte(xr2)] ^ c2.p[16]
	xl3 ^= ((c3.s0[byte(xr3>>24)] + c3.s1[byte(xr3>>16)]) ^ c3.s2[byte(xr3>>8)]) + c3.s3[byte(xr3)] ^ c3.p[16]
	xl4 ^= ((c4.s0[byte(xr4>>24)] + c4.s1[byte(xr4>>16)]) ^ c4.s2[byte(xr4>>8)]) + c4.s3[byte(xr4)] ^ c4.p[16]
	xl5 ^= ((c5.s0[byte(xr5>>24)] + c5.s1[byte(xr5>>16)]) ^ c5.s2[byte(xr5>>8)]) + c5.s3[byte(xr5)] ^ c5.p[16]
	xl6 ^= ((c6.s0[byte(xr6>>24)] + c6.s1[byte(xr6>>16)]) ^ c6.s2[byte(xr6>>8)]) + c6.s3[byte(xr6)] ^ c6.p[16]
	xl7 ^= ((c7.s0[byte(xr7>>24)] + c7.s1[byte(xr7>>16)]) ^ c7.s2[byte(xr7>>8)]) + c7.s3[byte(xr7)] ^ c7.p[16]
	xr0 ^= c0.p[17]
	xr1 ^= c1.p[17]
	xr2 ^= c2.p[17]
	xr3 ^= c3.p[17]
	xr4 ^= c4.p[17]
	xr5 ^= c5.p[17]
	xr6 ^= c6.p[17]
	xr7 ^= c7.p[17]
	return xr0, xl0, xr1, xl1, xr2, xl2, xr3, xl3, xr4, xl4, xr5, xl5, xr6, xl6, xr7, xl7
}

func expandKey8(keys [8][]byte, c [8]*state) {
	for i := 0; i < 18; i++ {
		c[0].p[i] ^= nextWord(keys[0], i*4)
		c[1].p[i] ^= nextWord(keys[1], i*4)
		c[2].p[i] ^= nextWord(keys[2], i*4)
		c[3].p[i] ^= nextWord(keys[3], i*4)
		c[4].p[i] ^= nextWord(keys[4], i*4)
		c[5].p[i] ^= nextWord(keys[5], i*4)
		c[6].p[i] ^= nextWord(keys[6], i*4)
		c[7].p[i] ^= nextWord(keys[7], i*4)
	}
	c0 := c[0]
	c1 := c[1]
	c2 := c[2]
	c3 := c[3]
	c4 := c[4]
	c5 := c[5]
	c6 := c[6]
	c7 := c[7]
	var l0, r0 uint32
	var l1, r1 uint32
	var l2, r2 uint32
	var l3, r3 uint32
	var l4, r4 uint32
	var l5, r5 uint32
	var l6, r6 uint32
	var l7, r7 uint32
	for i := 0; i < 18; i += 2 {
		l0, r0, l1, r1, l2, r2, l3, r3, l4, r4, l5, r5, l6, r6, l7, r7 = encryptBlock8(l0, r0, l1, r1, l2, r2, l3, r3, l4, r4, l5, r5, l6, r6, l7, r7, c0, c1, c2, c3, c4, c5, c6, c7)
		c0.p[i], c0.p[i+1] = l0, r0
		c1.p[i], c1.p[i+1] = l1, r1
		c2.p[i], c2.p[i+1] = l2, r2
		c3.p[i], c3.p[i+1] = l3, r3
		c4.p[i], c4.p[i+1] = l4, r4
		c5.p[i], c5.p[i+1] = l5, r5
		c6.p[i], c6.p[i+1] = l6, r6
		c7.p[i], c7.p[i+1] = l7, r7
	}
	for i := 0; i < 256; i += 2 {
		l0, r0, l1, r1, l2, r2, l3, r3, l4, r4, l5, r5, l6, r6, l7, r7 = encryptBlock8(l0, r0, l1, r1, l2, r2, l3, r3, l4, r4, l5, r5, l6, r6, l7, r7, c0, c1, c2, c3, c4, c5, c6, c7)
		c0.s0[i], c0.s0[i+1] = l0, r0
		c1.s0[i], c1.s0[i+1] = l1, r1
		c2.s0[i], c2.s0[i+1] = l2, r2
		c3.s0[i], c3.s0[i+1] = l3, r3
		c4.s0[i], c4.s0[i+1] = l4, r4
		c5.s0[i], c5.s0[i+1] = l5, r5
		c6.s0[i], c6.s0[i+1] = l6, r6
		c7.s0[i], c7.s0[i+1] = l7, r7
	}
	for i := 0; i < 256; i += 2 {
		l0, r0, l1, r1, l2, r2, l3, r3, l4, r4, l5, r5, l6, r6, l7, r7 = encryptBlock8(l0, r0, l1, r1, l2, r2, l3, r3, l4, r4, l5, r5, l6, r6, l7, r7, c0, c1, c2, c3, c4, c5, c6, c7)
		c0.s1[i], c0.s1[i+1] = l0, r0
		c1.s1[i], c1.s1[i+1] = l1, r1
		c2.s1[i], c2.s1[i+1] = l2, r2
		c3.s1[i], c3.s1[i+1] = l3, r3
		c4.s1[i], c4.s1[i+1] = l4, r4
		c5.s1[i], c5.s1[i+1] = l5, r5
		c6.s1[i], c6.s1[i+1] = l6, r6
		c7.s1[i], c7.s1[i+1] = l7, r7
	}
	for i := 0; i < 256; i += 2 {
		l0, r0, l1, r1, l2, r2, l3, r3, l4, r4, l5, r5, l6, r6, l7, r7 = encryptBlock8(l0, r0, l1, r1, l2, r2, l3, r3, l4, r4, l5, r5, l6, r6, l7, r7, c0, c1, c2, c3, c4, c5, c6, c7)
		c0.s2[i], c0.s2[i+1] = l0, r0
		c1.s2[i], c1.s2[i+1] = l1, r1
		c2.s2[i], c2.s2[i+1] = l2, r2
		c3.s2[i], c3.s2[i+1] = l3, r3
		c4.s2[i], c4.s2[i+1] = l4, r4
		c5.s2[i], c5.s2[i+1] = l5, r5
		c6.s2[i], c6.s2[i+1] = l6, r6
		c7.s2[i], c7.s2[i+1] = l7, r7
	}
	for i := 0; i < 256; i += 2 {
		l0, r0, l1, r1, l2, r2, l3, r3, l4, r4, l5, r5, l6, r6, l7, r7 = encryptBlock8(l0, r0, l1, r1, l2, r2, l3, r3, l4, r4, l5, r5, l6, r6, l7, r7, c0, c1, c2, c3, c4, c5, c6, c7)
		c0.s3[i], c0.s3[i+1] = l0, r0
		c1.s3[i], c1.s3[i+1] = l1, r1
		c2.s3[i], c2.s3[i+1] = l2, r2
		c3.s3[i], c3.s3[i+1] = l3, r3
		c4.s3[i], c4.s3[i+1] = l4, r4
		c5.s3[i], c5.s3[i+1] = l5, r5
		c6.s3[i], c6.s3[i+1] = l6, r6
		c7.s3[i], c7.s3[i+1] = l7, r7
	}
}

func expandKeyWithSalt8(keys [8][]byte, salt []byte, c [8]*state) {
	for i := 0; i < 18; i++ {
		c[0].p[i] ^= nextWord(keys[0], i*4)
		c[1].p[i] ^= nextWord(keys[1], i*4)
		c[2].p[i] ^= nextWord(keys[2], i*4)
		c[3].p[i] ^= nextWord(keys[3], i*4)
		c[4].p[i] ^= nextWord(keys[4], i*4)
		c[5].p[i] ^= nextWord(keys[5], i*4)
		c[6].p[i] ^= nextWord(keys[6], i*4)
		c[7].p[i] ^= nextWord(keys[7], i*4)
	}
	c0 := c[0]
	c1 := c[1]
	c2 := c[2]
	c3 := c[3]
	c4 := c[4]
	c5 := c[5]
	c6 := c[6]
	c7 := c[7]
	var l0, r0 uint32
	var l1, r1 uint32
	var l2, r2 uint32
	var l3, r3 uint32
	var l4, r4 uint32
	var l5, r5 uint32
	var l6, r6 uint32
	var l7, r7 uint32
	sj := 0
	for i := 0; i < 18; i += 2 {
		l0 ^= saltWord(salt, sj)
		r0 ^= saltWord(salt, sj+4)
		l1 ^= saltWord(salt, sj)
		r1 ^= saltWord(salt, sj+4)
		l2 ^= saltWord(salt, sj)
		r2 ^= saltWord(salt, sj+4)
		l3 ^= saltWord(salt, sj)
		r3 ^= saltWord(salt, sj+4)
		l4 ^= saltWord(salt, sj)
		r4 ^= saltWord(salt, sj+4)
		l5 ^= saltWord(salt, sj)
		r5 ^= saltWord(salt, sj+4)
		l6 ^= saltWord(salt, sj)
		r6 ^= saltWord(salt, sj+4)
		l7 ^= saltWord(salt, sj)
		r7 ^= saltWord(salt, sj+4)
		sj = (sj + 8) % len(salt)
		l0, r0, l1, r1, l2, r2, l3, r3, l4, r4, l5, r5, l6, r6, l7, r7 = encryptBlock8(l0, r0, l1, r1, l2, r2, l3, r3, l4, r4, l5, r5, l6, r6, l7, r7, c0, c1, c2, c3, c4, c5, c6, c7)
		c0.p[i], c0.p[i+1] = l0, r0
		c1.p[i], c1.p[i+1] = l1, r1
		c2.p[i], c2.p[i+1] = l2, r2
		c3.p[i], c3.p[i+1] = l3, r3
		c4.p[i], c4.p[i+1] = l4, r4
		c5.p[i], c5.p[i+1] = l5, r5
		c6.p[i], c6.p[i+1] = l6, r6
		c7.p[i], c7.p[i+1] = l7, r7
	}
	for i := 0; i < 256; i += 2 {
		l0 ^= saltWord(salt, sj)
		r0 ^= saltWord(salt, sj+4)
		l1 ^= saltWord(salt, sj)
		r1 ^= saltWord(salt, sj+4)
		l2 ^= saltWord(salt, sj)
		r2 ^= saltWord(salt, sj+4)
		l3 ^= saltWord(salt, sj)
		r3 ^= saltWord(salt, sj+4)
		l4 ^= saltWord(salt, sj)
		r4 ^= saltWord(salt, sj+4)
		l5 ^= saltWord(salt, sj)
		r5 ^= saltWord(salt, sj+4)
		l6 ^= saltWord(salt, sj)
		r6 ^= saltWord(salt, sj+4)
		l7 ^= saltWord(salt, sj)
		r7 ^= saltWord(salt, sj+4)
		sj = (sj + 8) % len(salt)
		l0, r0, l1, r1, l2, r2, l3, r3, l4, r4, l5, r5, l6, r6, l7, r7 = encryptBlock8(l0, r0, l1, r1, l2, r2, l3, r3, l4, r4, l5, r5, l6, r6, l7, r7, c0, c1, c2, c3, c4, c5, c6, c7)
		c0.s0[i], c0.s0[i+1] = l0, r0
		c1.s0[i], c1.s0[i+1] = l1, r1
		c2.s0[i], c2.s0[i+1] = l2, r2
		c3.s0[i], c3.s0[i+1] = l3, r3
		c4.s0[i], c4.s0[i+1] = l4, r4
		c5.s0[i], c5.s0[i+1] = l5, r5
		c6.s0[i], c6.s0[i+1] = l6, r6
		c7.s0[i], c7.s0[i+1] = l7, r7
	}
	for i := 0; i < 256; i += 2 {
		l0 ^= saltWord(salt, sj)
		r0 ^= saltWord(salt, sj+4)
		l1 ^= saltWord(salt, sj)
		r1 ^= saltWord(salt, sj+4)
		l2 ^= saltWord(salt, sj)
		r2 ^= saltWord(salt, sj+4)
		l3 ^= saltWord(salt, sj)
		r3 ^= saltWord(salt, sj+4)
		l4 ^= saltWord(salt, sj)
		r4 ^= saltWord(salt, sj+4)
		l5 ^= saltWord(salt, sj)
		r5 ^= saltWord(salt, sj+4)
		l6 ^= saltWord(salt, sj)
		r6 ^= saltWord(salt, sj+4)
		l7 ^= saltWord(salt, sj)
		r7 ^= saltWord(salt, sj+4)
		sj = (sj + 8) % len(salt)
		l0, r0, l1, r1, l2, r2, l3, r3, l4, r4, l5, r5, l6, r6, l7, r7 = encryptBlock8(l0, r0, l1, r1, l2, r2, l3, r3, l4, r4, l5, r5, l6, r6, l7, r7, c0, c1, c2, c3, c4, c5, c6, c7)
		c0.s1[i], c0.s1[i+1] = l0, r0
		c1.s1[i], c1.s1[i+1] = l1, r1
		c2.s1[i], c2.s1[i+1] = l2, r2
		c3.s1[i], c3.s1[i+1] = l3, r3
		c4.s1[i], c4.s1[i+1] = l4, r4
		c5.s1[i], c5.s1[i+1] = l5, r5
		c6.s1[i], c6.s1[i+1] = l6, r6
		c7.s1[i], c7.s1[i+1] = l7, r7
	}
	for i := 0; i < 256; i += 2 {
		l0 ^= saltWord(salt, sj)
		r0 ^= saltWord(salt, sj+4)
		l1 ^= saltWord(salt, sj)
		r1 ^= saltWord(salt, sj+4)
		l2 ^= saltWord(salt, sj)
		r2 ^= saltWord(salt, sj+4)
		l3 ^= saltWord(salt, sj)
		r3 ^= saltWord(salt, sj+4)
		l4 ^= saltWord(salt, sj)
		r4 ^= saltWord(salt, sj+4)
		l5 ^= saltWord(salt, sj)
		r5 ^= saltWord(salt, sj+4)
		l6 ^= saltWord(salt, sj)
		r6 ^= saltWord(salt, sj+4)
		l7 ^= saltWord(salt, sj)
		r7 ^= saltWord(salt, sj+4)
		sj = (sj + 8) % len(salt)
		l0, r0, l1, r1, l2, r2, l3, r3, l4, r4, l5, r5, l6, r6, l7, r7 = encryptBlock8(l0, r0, l1, r1, l2, r2, l3, r3, l4, r4, l5, r5, l6, r6, l7, r7, c0, c1, c2, c3, c4, c5, c6, c7)
		c0.s2[i], c0.s2[i+1] = l0, r0
		c1.s2[i], c1.s2[i+1] = l1, r1
		c2.s2[i], c2.s2[i+1] = l2, r2
		c3.s2[i], c3.s2[i+1] = l3, r3
		c4.s2[i], c4.s2[i+1] = l4, r4
		c5.s2[i], c5.s2[i+1] = l5, r5
		c6.s2[i], c6.s2[i+1] = l6, r6
		c7.s2[i], c7.s2[i+1] = l7, r7
	}
	for i := 0; i < 256; i += 2 {
		l0 ^= saltWord(salt, sj)
		r0 ^= saltWord(salt, sj+4)
		l1 ^= saltWord(salt, sj)
		r1 ^= saltWord(salt, sj+4)
		l2 ^= saltWord(salt, sj)
		r2 ^= saltWord(salt, sj+4)
		l3 ^= saltWord(salt, sj)
		r3 ^= saltWord(salt, sj+4)
		l4 ^= saltWord(salt, sj)
		r4 ^= saltWord(salt, sj+4)
		l5 ^= saltWord(salt, sj)
		r5 ^= saltWord(salt, sj+4)
		l6 ^= saltWord(salt, sj)
		r6 ^= saltWord(salt, sj+4)
		l7 ^= saltWord(salt, sj)
		r7 ^= saltWord(salt, sj+4)
		sj = (sj + 8) % len(salt)
		l0, r0, l1, r1, l2, r2, l3, r3, l4, r4, l5, r5, l6, r6, l7, r7 = encryptBlock8(l0, r0, l1, r1, l2, r2, l3, r3, l4, r4, l5, r5, l6, r6, l7, r7, c0, c1, c2, c3, c4, c5, c6, c7)
		c0.s3[i], c0.s3[i+1] = l0, r0
		c1.s3[i], c1.s3[i+1] = l1, r1
		c2.s3[i], c2.s3[i+1] = l2, r2
		c3.s3[i], c3.s3[i+1] = l3, r3
		c4.s3[i], c4.s3[i+1] = l4, r4
		c5.s3[i], c5.s3[i+1] = l5, r5
		c6.s3[i], c6.s3[i+1] = l6, r6
		c7.s3[i], c7.s3[i+1] = l7, r7
	}
}

// run8 hashes exactly 8 candidates through interleaved lanes,
// writing verdicts to h.verdicts[:8].
func (h *Hasher) run8(pw [][]byte) {
	var keys [8][]byte
	var c [8]*state
	for i := 0; i < 8; i++ {
		// bug compatibility: the key's trailing NUL participates
		k := append(h.keyScratch[i][:0], pw[i]...)
		k = append(k, 0)
		h.keyScratch[i] = k
		keys[i] = k
		// no zeroing: initState overwrites p and s0..s3 in full;
		// clearing 4 KB per lane per batch would be pure waste.
		c[i] = &h.scratch[i]
		initState(c[i])
	}
	salt := h.csalt[:]
	expandKeyWithSalt8(keys, salt, c)
	var saltKeys [8][]byte
	for i := 0; i < 8; i++ {
		saltKeys[i] = salt
	}
	for r, rounds := uint64(0), uint64(1)<<uint(h.cost); r < rounds; r++ {
		expandKey8(keys, c)
		expandKey8(saltKeys, c)
	}
	for i := 0; i < 8; i++ {
		h.verdicts[i] = h.finish(c[i])
	}
}
